// Daystone: knižnica otázok na dnešný večer (rameno B testu, 2. 10. 2026).
// Tón podľa KONCEPT 7.4: pozvanie, nie príkaz; bez pohlavia; bez sexu, cyklu, zdravia,
// partnerových peňazí a bolestivých tém; žiadne testy partnera ani skóre (3-PRODUKT časť 6).
// Vlastné texty, nie 36 otázok Arona ani balíčky konkurencie. id sa nikdy nemení,
// lebo ho nesú odkazy, ktoré si ľudia už poslali.

export const TONY = {
  cozy: 'Cozy',
  playful: 'Playful',
  romance: 'Romance',
  loved: 'Feeling loved',
  ordinary: 'Ordinary moments',
  adventure: 'Small adventures',
};

const ZOZNAM = {
  cozy: [
    'What would a perfect lazy Sunday together look like, hour by hour?',
    'Which blanket, mug or sweater of ours feels most like home to you?',
    'If we stayed in tonight, what would we eat and what would we watch?',
    'What small sound in our home would you miss if it disappeared?',
    'Rain on the window or snow outside: which one makes you want to stay in with me?',
    'Where is your favorite spot to sit when we are both at home?',
    'Which song would you put on for a slow evening with just us?',
    'What is the coziest thing we have ever done on a cold day?',
    'Tea, coffee or hot chocolate for a long talk tonight, and why?',
    'What could we add to our evenings to make them a little softer?',
    'Which smell reminds you of a calm day with me?',
    'What tiny ritual of ours makes a day feel finished?',
    'Breakfast in bed or a slow breakfast at the table: which one, and what is on the plate?',
    'What would you like us to do more of on quiet evenings?',
    'Which book, show or game would you like to share with me this month?',
    'If we built a blanket fort tonight, what would we bring inside?',
  ],
  playful: [
    'What is something I do that still makes you smile without trying?',
    'When did you last look at me and think, yes, that one?',
    'Which outfit of mine would you pick for a surprise date?',
    'What was the very first thing you noticed about me?',
    'If you could replay one of our kisses, which one would it be?',
    'What compliment have you wanted to give me but never said out loud?',
    'Which of my habits secretly charms you?',
    'If we had a secret signal across a crowded room, what would it be?',
    'What is the most charming little mistake I have made in front of you?',
    'Describe me in three words, nice ones only.',
    'What would you write on a note to hide in my coat pocket?',
    'Which moment made you realize you had a crush on me?',
    'What is your favorite way I say your name?',
    'If we met as strangers at a cafe tonight, what would your opening line be?',
    'Which song makes you think of me in a slightly silly way?',
    'What tiny thing could I do tomorrow that would make you blush?',
  ],
  romance: [
    'Which moment with me would you like to live once more, exactly as it was?',
    'Where would you take me for one perfect evening if distance did not matter?',
    'What does a romantic day look like to you, from morning to night?',
    'Which small gesture of mine has stayed with you the longest?',
    'What would you like us to celebrate that we usually forget?',
    'If you wrote me a letter tonight, what would the first line say?',
    'Which place feels like ours to you, and why?',
    'What is the most romantic thing someone can do without spending any money?',
    'When do you feel closest to me?',
    'Which new tradition would you like us to start this year?',
    'A slow dance in our kitchen: which song, and which light?',
    'What is a small but real promise you would like to make me?',
    'Which photo of us would you put in a frame, and why that one?',
    'What is something about us you hope never changes?',
    'Where would you like us to watch a sunset someday?',
    'What do you remember feeling the first time we held hands?',
  ],
  loved: [
    'What one small thing makes you feel loved on a busy day?',
    'Which reaches you most this week: kind words, a hug, a bit of help, or time together?',
    'What message from me would you love to get at lunchtime?',
    'Which chore could I take off your list that would feel like a gift?',
    'What kind of hug do you like best: long, tight, from behind, or quick and often?',
    'What did I do recently that made you feel looked after?',
    'How do you like to be cheered on when something is hard?',
    'What is your favorite way to spend twenty minutes of undivided time with me?',
    'What little gift that costs almost nothing would make you smile?',
    'When you are tired, what helps more: talking, quiet company, or something done for you?',
    'Which words from me would you like to hear more often?',
    'How could I tell, without asking, that you would like a little extra care?',
    'When I tell you I am proud of you, what makes it really land?',
    'Which way of showing love comes easiest to you, and which would you like to try?',
    'What is one thing I do that makes you feel chosen?',
    'If today needed one kind act from me, what would it be?',
  ],
  ordinary: [
    'What ordinary moment from this week would you like to remember?',
    'What did you notice today that nobody else probably did?',
    'Which part of our usual morning do you like most?',
    'What in our home tells our story without words?',
    'What was the funniest small thing that happened to you today?',
    'If someone filmed one normal Tuesday of ours, which scene would you keep?',
    'Which dish do we make so often that it has become ours?',
    'Which everyday object would you keep forever because of us?',
    'Which phrase do we say so often that only we understand it?',
    'What were the best five minutes of your day?',
    'Which walk or route do you love doing with me?',
    'Which small habit of mine would you miss if you were away?',
    'What did today smell, sound or taste like?',
    'What tiny win from today have you not told me about yet?',
    'What normal thing do we do that you find quietly beautiful?',
    'If you took one photo of today, what would be in it?',
  ],
  adventure: [
    'Which place within an hour of home have we never been to together?',
    'If we had a free Saturday and no plan, what would you want to try first?',
    'Which food have neither of us tasted that we could try this month?',
    'A sunrise walk or a late night stroll: which small adventure do you choose?',
    'What skill could we learn together in one afternoon?',
    'If we got on the next train with no plan, where would you hope it goes?',
    'Which free thing in our town do we keep saying we will do?',
    'Picnic on the living room floor, on a balcony or in a park: where is our next one?',
    'Which game from when you were little would you like to teach me?',
    'If I gave you two hours tonight, which tiny trip would you plan?',
    'What new thing would you like us to try before the end of the year?',
    'Which dish from a country we have never visited should we cook together?',
    'Which hill, view or rooftop would you like to see with me?',
    'If we made a list of ten tiny adventures, what goes first?',
    'What brave little thing would you like to try with me next to you?',
    'What would a yes day look like, where we say yes to small ideas all day?',
  ],
};

export const OTAZKY = Object.entries(ZOZNAM).flatMap(([ton, texty]) =>
  texty.map((text, i) => ({ id: `${ton}-${String(i + 1).padStart(2, '0')}`, ton, text })));

export const PODLA_ID = new Map(OTAZKY.map((o) => [o.id, o]));
