// TO: NULL: 300 ručne písaných viet nedoručených listov z Lowmere (SPEC 2.7). Fikcia, malé písmená, najviac 44 znakov.
// Žiadne skutočné osoby, značky ani miesta mimo Lowmere. Smútok vždy s nádejou.

export const ULICE = ['quay road', 'hill steps', 'mill row', 'ferry lane', 'rope walk', 'salt yard', 'lantern street', 'tidewall'];

export const INICIALY = 'abcdefghijklmnoprstvw'.split('');

export const LISTY = [
  'the kettle is on. come home when you can.',
  "got the job. don't tell mom yet.",
  'sorry about tuesday. i was tired, not angry.',
  'the cat found the sunny chair again.',
  "bring the blue umbrella back. it was dad's.",
  'i planted the tomatoes too early. again.',
  'we named her after your mother.',
  "the boat's in. saturday at the quay?",
  'i still have your scarf. i wear it.',
  'tell grandma the stairs are fixed.',
  'first snow on the hill. thought of you.',
  'i passed. i actually passed.',
  'the bakery kept your usual for you.',
  'you left the radio on. i left it on too.',
  'call when the ferry lands.',
  "i was wrong about the paint. it's lovely.",
  "dinner at seven. i'm making the soup.",
  'we miss you at the table.',
  "the garden gate squeaks. don't fix it.",
  'my hands are better. i can knit again.',
  'happy birthday, old friend.',
  'the new flat has a window facing east.',
  'i found the photo from the harbor fair.',
  'come to the recital. third row, left.',
  "we're keeping the light on for you.",
  'your brother learned to whistle. finally.',
  'thank you for the letter. it helped.',
  "the tram is late, so i'm writing.",
  'i made your bread. it sank. i ate it.',
  'the dog waits by the door at six.',
  'the rain stopped. the street smells new.',
  'i kept the ticket stub. of course i did.',
  "i'm sorry i didn't come. next time.",
  'mum says the roses came back.',
  "we painted the boat green. don't laugh.",
  'i hope the night shift is quiet.',
  'the choir needs a tenor. hint.',
  "there's soup in the freezer with your name.",
  'i can see your window from the bridge.',
  'the fair is back. same rides, older us.',
  'thank you for waiting.',
  'i said yes.',
  'the baby laughed today. at everything.',
  'your coat is still on the hook.',
  'the fishing was bad. the company was good.',
  'keep warm. write back.',
  "fixed the bike. it's yours when you're back.",
  "i'll wait on the bench by the lamp.",
  "the door's open. it always was.",
  "i'm keeping the light on for you.",
  'the swallows are back under the roof.',
  'i learned your song on the old piano.',
  'the market had pears. i bought too many.',
  'your sister won the rowing race.',
  "we moved the table to the window. it's nice.",
  'finished the book you lent me. cried twice.',
  'the lighthouse keeper asked about you.',
  'my first pay. i bought mum a teapot.',
  "the stairs still creak on the fourth step.",
  'i miss our walks along the tidewall.',
  'the kids made a kite from your old map.',
  'the doctor says i am fine. really fine.',
  'i kept your seat at the harbor bench.',
  'we have a new neighbor. she bakes.',
  'the clock tower works again. it chimed.',
  'i wrote this twice. this one is better.',
  "your plants are alive. i'm shocked too.",
  'come for the lantern walk. bring gloves.',
  "i'm learning to swim. at my age.",
  'the tide took my hat. i let it go.',
  'we saved you a slice of the wedding cake.',
  'i found your glasses in the bread box.',
  'the bus driver still waves at me.',
  "grandpa says hello. he means it.",
  'planted the bulbs you sent. wait for spring.',
  "the ferry horn woke me. i didn't mind.",
  'we fixed the leak. the ceiling is dry.',
  'i am proud of you. i should say it more.',
  'the school play was a mess. a lovely mess.',
  'your old room is a sewing room now. sorry.',
  'the cherry tree bloomed early this year.',
  'i met someone kind. you would like him.',
  'the rope walk is lit up for the festival.',
  'write me the recipe. mine keeps burning.',
  'the gulls stole my chips. all of them.',
  'the harbor froze at the edges last night.',
  'i sold the old car. bought a bicycle.',
  "the twins can read now. watch out.",
  'i sang at the salt yard dance. badly.',
  'thank you for the socks. they are perfect.',
  'the post office lost my parcel. i laughed.',
  "your brother's boat is the red one now.",
  'the owl is back in the mill roof.',
  'i practiced the speech. i was ready.',
  'the first strawberries. i saved you three.',
  'we still play cards on thursdays.',
  'come back for the summer. there is room.',
  'i drew the harbor from the hill. for you.',
  'the fog lifted by noon. clear all day.',
  'mum is making plum jam. the house smells.',
  'i found a shell with a hole. it whistles.',
  "we're a team of three now. the dog votes.",
  'the library kept your card. still valid.',
  'the new bridge opened. we walked across.',
  "i'm sorry about the plate. it was ugly.",
  'the storm passed. everyone is fine.',
  'i finally fixed the kitchen chair.',
  'the tea shop remembers how you take it.',
  'they gave me the keys to the boathouse.',
  "i wear your watch. still two minutes slow.",
  'the kids ask when you visit. soon?',
  'we lit a candle in the window for you.',
  'your letter arrived wet. i dried it.',
  'i passed the driving test. third time.',
  'the old ferry got a new coat of paint.',
  'dad hums your song when he cooks.',
  'the orchard gave twelve baskets this year.',
  'i miss your terrible jokes. send some.',
  'the lamp by the bench is fixed now.',
  'i taught the parrot your name. sorry.',
  'we danced in the kitchen. no music.',
  'the cake fell. we ate it with spoons.',
  'i hope your feet are warm tonight.',
  'the town bell rang for the new baby.',
  'grandma beat everyone at chess again.',
  'i kept the jar of buttons. all of them.',
  'the snow is up to the gate. we are cozy.',
  'i found your name carved in the old desk.',
  'the fishermen say the cod are back.',
  'we got the piano up the stairs. somehow.',
  'your nephew said his first word. ball.',
  'the harbor lights look like beads tonight.',
  'i miss arguing with you about the news.',
  'the shop on mill row sells your cheese.',
  'the stars were loud last night. no clouds.',
  'i kept your bike tires pumped. just in case.',
  "the roof is new. it doesn't sing anymore.",
  'thank you for sitting with me that night.',
  'we are fine. truly. eat something warm.',
  'i put your drawing on the fridge.',
  'the kitten sleeps in your boots.',
  'the ferry lane cafe has new chairs.',
  'i finished the quilt. it has your blue.',
  'the neighbor fixed our fence for free.',
  'i got the apartment with the tall stairs.',
  'the river is high. the ducks are thrilled.',
  "i've started walking to work. i like it.",
  'won a goldfish at the fair. his name is tim.',
  'come home for the harvest supper.',
  'i promise to answer faster this time.',
  "mum forgives you. she said so. twice.",
  'the lantern street parade was lovely.',
  'we kept the swing on the old oak.',
  'i opened the window. spring came in.',
  'the bread came out right. finally.',
  'i remembered your birthday a day late.',
  'my garden has one carrot. it is huge.',
  'the sea was flat as a plate this morning.',
  'i love you. that is the whole letter.',
  'the choir sang the tune you always hummed.',
  'your umbrella is still at our door.',
  "new curtains. mum picked. they're loud.",
  'the tidewall path is open again.',
  'i found a coin from the year you were born.',
  'the blackbird sings at four. every day.',
  'your old teacher asked if you still draw.',
  'i made a new friend at the salt yard.',
  'the pantry is full. come eat it.',
  'my knee is better. i climbed the hill steps.',
  'the dog found your ball behind the shed.',
  'we framed the photo from the pier.',
  'the soup is on. the door is not locked.',
  'the stairs to your room have a rail now.',
  'i wrote you a poem. it is short. it rhymes.',
  'thank you for the seeds. they came up.',
  'the market bell rang at noon. i missed you.',
  'i painted the gate yellow. you were right.',
  'the storm took the washing. we found it.',
  'your sister is engaged. act surprised.',
  'we held the picnic in the rain. worth it.',
  'the harbor master retired. big party.',
  'i finally learned to make your pie.',
  'the baby sleeps through the night now.',
  'your radio still plays. only one station.',
  'i miss the sound of you reading aloud.',
  'the boats came home early. calm sea.',
  'i kept a candle for you at the window.',
  'we are saving for the trip. slowly.',
  'the moon was orange over the quay.',
  'the cafe owner asked where you went.',
  "i bought the good coffee. don't tell dad.",
  'the new baby has your ears.',
  'your coat got a new button. green one.',
  'the kids built a fort under the table.',
  'we went sledding on the hill. i fell.',
  'i am not angry. i was never angry.',
  'the garden is wild. we like it that way.',
  'i made tea for two out of habit.',
  'the mill wheel turns again. they fixed it.',
  'come see the new lamp in the square.',
  'i found the letter you wrote at ten.',
  'your cousin opened a bakery on quay road.',
  'the bench by the lamp has a plaque now.',
  "i'm better at waiting than i used to be.",
  'we still set a place for you on sundays.',
  'the herons are nesting by the ferry lane.',
  'my sister taught me to fish. i caught one.',
  'the wind turned. it smells like the sea.',
  'i kept the stamps from all your letters.',
  'the path to the beach has steps now.',
  'dinner was burnt. we laughed all night.',
  'thank you for looking after mum.',
  'the dog learned to open the gate. help.',
  'i passed the old house. the lights were on.',
  'the fisherman gave us a fish. for free.',
  'i hope the city is kind to you.',
  'your drawing won a ribbon at the fair.',
  'the swallows left today. they come back.',
  'we cleaned the attic. found your skates.',
  'i am sending jam. eat it with bread.',
  'the tram got a new bell. it sounds silly.',
  'we are all right here. just a bit quiet.',
  'i read your letter till the paper went soft.',
  'the pier lights were fixed before winter.',
  'your little brother grew. you will see.',
  'the first frost. i covered your roses.',
  'i got the choir solo. come and hear it.',
  'the salt yard bell rings at dusk now.',
  'i knitted you a hat. it is too big.',
  'we painted the kitchen the color of sand.',
  "i'm writing from the ferry. it rocks.",
  'the market fish man asked for you.',
  'the old oak lost a branch. still standing.',
  'i planted a tree for the new baby.',
  'we went to the lighthouse. windy. lovely.',
  'thank you for the long call on friday.',
  'your chair is waiting by the stove.',
  'i ride the early tram now. it is quiet.',
  'we found your old kite in the shed.',
  'the snow melted. mud everywhere. happy.',
  'the fair had a band. we danced badly.',
  'i found a job at the rope walk. good hours.',
  'mum laughed today. really laughed.',
  'the bridge lamps are on. walk home safe.',
  'i saved the first cherry for you.',
  'the ducks followed me home. all six.',
  'we sang your song at the party.',
  'the house is warm. come home.',
  "i'll meet the late ferry. every night.",
  'your garden chair survived the storm.',
  'i baked your cake. it was almost right.',
  'the stars on the hill are worth the climb.',
  'i finally visited the harbor museum.',
  'the kettle whistles like it used to.',
  'thank you for the flowers. still blooming.',
  'we named the new boat after you.',
  'the fog horn sounded twice. then sun.',
  'i wrote your name in the sand. it stayed.',
  'your brother is kinder than he lets on.',
  'the rain on the roof sounds like you typing.',
  'i see the harbor lights. goodnight.',
  'bring nothing. just come.',
  'the orchard needs pickers. and you.',
  'the old radio found a new station.',
  "i'm sorry. i miss you. both are true.",
  'the ferry lane lamps glow green tonight.',
  'we found the missing key. in the teapot.',
  'i swam in the sea. cold. glorious.',
  'the owl sat on the gate all evening.',
  'your mug is still on the second shelf.',
  'i learned to bake rye. it tastes of home.',
  'the pier had music all night.',
  'we got a letter from you. we read it twice.',
  'the snowdrops came up by the step.',
  "tell me when you're coming. i'll bake.",
  'i hung your painting over the stove.',
  'the hill steps have a new rail.',
  "the town's quieter without you. not worse.",
  'i took the long way home. past your street.',
  'the moon came out for the lantern walk.',
  'the dog is old now. still waits at six.',
  'we planted beans. they climbed the fence.',
  'i kept the window seat warm for you.',
  'the ferry is on time for once.',
  'the jam turned out. i sent two jars.',
  'the cafe on tidewall plays your records.',
  'i finally slept all night. all of it.',
  'write when you can. no rush.',
  'the gulls are loud. the sea is calm.',
  'see you at the quay. i will wave.',
  'the kids asked for your story again.',
  'i mended the net. it holds now.',
  'the bakery on hill steps opens at five.',
  'your cat chose me. i am honored.',
  'we cut the hedge into a boat. it looks odd.',
  'the lamp in the hall is yours. it glows.',
  'i found the path you told me about.',
  'the tidewall wind nearly took my letter.',
  'i kept the porch light on all week.',
  'come home slowly. we are not going anywhere.',
];
