export const jazyky = { sk: 'Slovenčina', cs: 'Čeština', en: 'English', de: 'Deutsch' };
export const cesta = j => '/rukopis/' + (j === 'sk' ? '' : j + '/');
export const texty = {
  sk: {
    autoShort: "Automaticky",
    rhythmEven: "Vety majú podobnú dĺžku, text môže znieť monotónne.",
    rhythmVaried: "Dĺžka viet sa mení, rytmus je pestrejší.",
    rhythmFew: "Na hodnotenie rytmu treba aspoň 80 slov a 5 viet.",
    rhythmHint: "Ťuknite na stĺpec alebo ho vyberte klávesom Tab. Graf možno posúvať.",
    average: "Priemer",
    uniform: "Rovnomerné",
    sentence: "Veta",
    title: 'Rukopis: nájdite šablónové frázy vo svojom texte',
    heading: 'Menej fráz. Viac vášho hlasu.',
    lead: 'Zistite, kde text znie všeobecne a čo upraviť ako prvé.',
    badge: 'Rukopis · bezplatné meranie', tool: 'Meranie textu', example: 'Príklad', own: 'Vložiť vlastný text', undo: 'Vrátiť text', load: 'Načítať príklad',
    measure: 'Zmerať text zadarmo', label: 'Text na meranie', language: 'Jazyk textu', auto: 'Rozpoznať automaticky', detected: 'Rozpoznaný jazyk', selected: 'Zvolený jazyk',
    privacy: 'Text ostáva v prehliadači.', free: '0 € meranie, bez registrácie', index: 'Index uhladenosti',
    bands: ['živý', 'zmiešaný', 'príliš uhladený'], partial: 'čiastočný index',
    calibration: 'Orientačné prahy, zatiaľ nekalibrované.', meaning: 'Číslo opisuje štýl, neurčuje autora. Vyššie číslo znamená viac šablónových znakov.',
    words: 'slov', sentences: 'viet', version: 'verzia', rhythm: 'Dĺžky viet v slovách', numbers: 'Číselné hodnoty grafu',
    findings: 'Nálezy v texte', hint: 'Ťuknite na zvýraznené miesto alebo naň prejdite klávesom Tab.', first: 'Čo opraviť najprv', jump: 'Prvý výskyt',
    details: 'Podrobné merania', unmeasured: 'Nemerané: treba 80 slov, pri rytme 5 viet a pri odsekoch 3 odseky.',
    nofindings: 'Žiadne nálezy na zvýraznenie. Skontrolujte ešte, či text hovorí niečo konkrétne.',
    low: 'Doplňte aspoň 30 slov tela bez nadpisu.', choose: 'Jazyk nie je jednoznačný. Vyberte ho pri texte.', error: 'Meranie sa nepodarilo. Skúste text vložiť znova.',
    done: 'Meranie hotové.', truncated: 'Meriame iba prvých 5 000 slov tela.',
    copy: 'Kopírovať správu', copied: 'Správa skopírovaná.', fallback: 'Schránka nie je dostupná. Označenú správu skopírujte cez Ctrl+C alebo ponuku telefónu.', close: 'Zavrieť', report: 'Správa z merania',
    provenance: 'Príklad od Claude (Anthropic), 29. 9. 2026. Ilustrácia štýlu, nie kalibračná vzorka ani vecná rada.',
    about: 'Ako čítať výsledok', aboutText: 'Začnite zvýrazneným miestom. Rada je podnet na vlastnú úpravu, nie povinnosť odstrániť každú frázu. Od 30 do 79 slov meriame len frázy, pomlčky, nominalizácie a trojice. Rovnaký text, jazyk a verzia dávajú rovnaké výsledky.',
    future: 'Prepis vaším hlasom, profil a porovnanie verzií pripravujeme. Teraz je dostupné meranie, bez účtu a bez platby.',
    faq: 'Časté otázky', watermark: 'Odstráni Rukopis vodoznak Claude?', watermarkText: 'Nie. Rukopis vodoznak Claude neoveruje ani neodstraňuje. Nesľubuje obchádzanie kontrol. Pomáha upraviť štýl vlastnými slovami.',
    author: 'Dokáže číslo určiť autora?', authorText: 'Nie. Aj človek používa šablónové frázy. Index je orientačná pomôcka na úpravu štýlu, nie dôkaz pôvodu textu.',
    languages: 'Ktoré jazyky sa merajú?', languagesText: 'Slovenčina, čeština, angličtina a nemčina. Automatický odhad môžete vždy zmeniť. Pri krátkom alebo zmiešanom texte vyberte jazyk ručne.',
    data: 'Čo sa deje s textom?', dataText: 'Spracúva sa len v tomto prehliadači. Neukladáme ho do histórie ani neposielame na server. Anonymné meranie použitia obsahuje iba jazyk, pásmo a veľkostné vedro. Správu kopírujete len svojím tlačidlom.',
    sources: 'Podklady a hranice', sourcesText: 'StoryScope, Reinhart et al. a LAMP sú podklady pre pracovné hypotézy, nie kalibrácia nášho indexu. Trojice sú vlastná hypotéza. Zhoda s frázou neurčuje autorstvo.',
    metrics: ['Rytmus viet','Rovnomernosť odsekov','Pointa na konci','Odbočky a konkrétnosti','Otvorenosť','Šablónové frázy','Pomlčky','Nominalizácie','Trojice'],
    types: ['frázy','pointa','trojice','nominalizácie','pomlčky','konkrétnosti','otvorenosť'],
    advice: [
      ['Podobné dĺžky viet môžu pôsobiť jednotvárne.','Skráťte jednu vetu tak, aby zostala jej hlavná myšlienka.'],
      ['Rovnako dlhé odseky môžu zakryť rozdiely medzi myšlienkami.','Oddeľte nový argument do samostatného odseku.'],
      ['Záverečné poučenie môže opakovať to, čo už čitateľ pochopil.','Vymažte záverečnú radu, ak nepridáva novú informáciu.'],
      ['Málo konkrétnych údajov môže znieť všeobecne; samotné meno nič nedokazuje.','Pridajte jeden doložiteľný príklad z vašej firmy.'],
      ['Text neukazuje veľa otázok ani neistoty. To samo osebe nie je chyba.','Ak existuje nejasnosť, pomenujte presne, čo ešte neviete.'],
      ['Táto formulácia je v našom zozname často opakovaných fráz.','Nahraďte ju jedným konkrétnym príkladom z vašej firmy.'],
      ['Časté pomlčky môžu vytvárať opakujúci sa rytmus.','Skúste na tomto mieste bodku a dve kratšie vety.'],
      ['Prípona naznačuje abstraktné podstatné meno, nie vždy správne.','Pomenujte človeka a sloveso: kto presne čo urobil?'],
      ['Trojčlenný výpočet môže znieť naučene. Je to pracovná hypotéza.','Ponechajte najdôležitejší bod a doložte ho príkladom.']
    ]
  },
  en: {
    autoShort: "Automatic",
    rhythmEven: "Sentence lengths are similar, which can sound monotonous.",
    rhythmVaried: "Sentence lengths vary, giving the text a more varied rhythm.",
    rhythmFew: "Rhythm needs at least 80 words and 5 sentences to be assessed.",
    rhythmHint: "Tap a bar or use Tab to select it. The chart can scroll.",
    average: "Average",
    uniform: "Uniform",
    sentence: "Sentence",
    title: 'Rukopis: find stock phrases in your writing', heading: 'Less stock phrasing. More of you.', lead: 'See where your writing gets vague, and where to start editing.',
    badge: 'Rukopis · free writing check', tool: 'Writing check', example: 'Example', own: 'Use my own text', undo: 'Restore text', load: 'Load example',
    measure: 'Check my writing', label: 'Text to check', language: 'Text language', auto: 'Detect automatically', detected: 'Detected language', selected: 'Selected language',
    privacy: 'Your text stays in your browser.', free: '€0 to check, no account', index: 'Polish index', bands: ['lively','mixed','too polished'], partial: 'partial score',
    calibration: 'Provisional thresholds, not yet calibrated.', meaning: 'This describes style, not authorship. Higher scores mean more formulaic features.',
    words: 'words', sentences: 'sentences', version: 'version', rhythm: 'Sentence lengths in words', numbers: 'Chart values', findings: 'Inside your text', hint: 'Tap a highlighted passage or reach it with Tab.', first: 'Where to start', jump: 'First occurrence', details: 'Detailed measurements', unmeasured: 'Not measured: needs 80 words, 5 sentences for rhythm and 3 paragraphs for paragraph length.',
    nofindings: 'No passages to highlight. Still check whether your text says something specific.', low: 'Add at least 30 body words, excluding the heading.', choose: 'The language is unclear. Choose it next to your text.', error: 'Could not check the text. Please paste it again.', done: 'Check complete.', truncated: 'Only the first 5,000 body words are measured.',
    copy: 'Copy report', copied: 'Report copied.', fallback: 'Clipboard access is unavailable. Copy the selected report with Ctrl+C or your phone’s selection menu.', close: 'Close', report: 'Writing report',
    provenance: 'Example by Claude (Anthropic), 29 September 2026. A style illustration, not a calibration sample or factual advice.',
    about: 'Reading your results', aboutText: 'Start with a highlighted passage. Each suggestion is an editing prompt, not a rule to remove every phrase. Texts of 30 to 79 words receive only phrase, dash, nominalisation and list checks. The same text, language and version produce the same result.',
    future: 'Voice profiles, rewriting and version comparisons are in preparation. The writing check is available now, with no account or payment.',
    faq: 'Questions', watermark: 'Does Rukopis remove Claude’s watermark?', watermarkText: 'No. Rukopis neither verifies nor removes Claude’s watermark. It does not promise to bypass checks. It helps you revise the style in your own words.',
    author: 'Can a score identify the author?', authorText: 'No. People use stock phrases too. The index is a provisional editing aid, not evidence of where a text came from.',
    languages: 'Which languages can I check?', languagesText: 'Slovak, Czech, English and German. You can override automatic detection at any time. Choose manually for short or mixed-language writing.',
    data: 'What happens to my text?', dataText: 'It is processed only in this browser. We do not save it to a history or send it to a server. Anonymous usage events contain only language, score band and length bucket. Copying a report requires your click.',
    sources: 'Evidence and limits', sourcesText: 'StoryScope, Reinhart et al. and LAMP inform working hypotheses; they do not validate our index. Lists of three are our own hypothesis. A phrase match says nothing about authorship.',
    metrics: ['Sentence rhythm','Paragraph uniformity','Closing message','Asides and specifics','Openness','Stock phrases','Dashes','Nominalisations','Lists of three'],
    types: ['stock phrases','closing message','lists of three','nominalisations','dashes','specific details','openness'],
    advice: [
      ['Similar sentence lengths can sound repetitive.','Shorten one sentence while keeping its main point.'],
      ['Uniform paragraphs can hide changes in the argument.','Give a new argument its own paragraph.'],
      ['A closing lesson may repeat what the reader already understood.','Remove the final advice if it adds no new information.'],
      ['Few concrete details can make writing vague; a name alone proves nothing.','Add one example from your business that you can substantiate.'],
      ['There are few questions or admissions of uncertainty. That is not inherently wrong.','If something is uncertain, say exactly what you do not know.'],
      ['This wording matches our list of commonly repeated phrases.','Replace it with one concrete example from your business.'],
      ['Frequent dashes can create a repetitive rhythm.','Try a full stop and two shorter sentences here.'],
      ['The suffix suggests an abstract noun; this heuristic can be wrong.','Name the person and action: who did what?'],
      ['Three-part lists can sound rehearsed. This is a working hypothesis.','Keep the strongest point and support it with an example.']
    ]
  },
  cs: {
    autoShort: "Automaticky",
    rhythmEven: "Věty mají podobnou délku, text může znít jednotvárně.",
    rhythmVaried: "Délka vět se mění, rytmus je pestřejší.",
    rhythmFew: "Pro hodnocení rytmu je třeba alespoň 80 slov a 5 vět.",
    rhythmHint: "Klepněte na sloupec nebo jej vyberte klávesou Tab. Graf lze posouvat.",
    average: "Průměr",
    uniform: "Rovnoměrné",
    sentence: "Věta",
    title: 'Rukopis: najděte šablonovité fráze ve svém textu', heading: 'Méně frází. Více vašeho hlasu.', lead: 'Podívejte se, kde text zní obecně a co upravit jako první.',
    badge: 'Rukopis · měření zdarma', tool: 'Měření textu', example: 'Příklad', own: 'Vložit vlastní text', undo: 'Vrátit text', load: 'Načíst příklad',
    measure: 'Změřit text zdarma', label: 'Text k měření', language: 'Jazyk textu', auto: 'Rozpoznat automaticky', detected: 'Rozpoznaný jazyk', selected: 'Zvolený jazyk',
    privacy: 'Text zůstává v prohlížeči.', free: '0 € měření, bez registrace', index: 'Index uhlazenosti', bands: ['živý','smíšený','příliš uhlazený'], partial: 'částečný index',
    calibration: 'Orientační prahy, zatím nekalibrované.', meaning: 'Číslo popisuje styl, neurčuje autora. Vyšší číslo znamená více šablonovitých znaků.',
    words: 'slov', sentences: 'vět', version: 'verze', rhythm: 'Délky vět ve slovech', numbers: 'Číselné hodnoty grafu', findings: 'Nálezy v textu', hint: 'Klepněte na zvýrazněné místo nebo na ně přejděte klávesou Tab.', first: 'Co upravit nejdřív', jump: 'První výskyt', details: 'Podrobná měření', unmeasured: 'Neměřeno: je třeba 80 slov, pro rytmus 5 vět a pro odstavce 3 odstavce.',
    nofindings: 'Žádné nálezy ke zvýraznění. Ještě ověřte, zda text říká něco konkrétního.', low: 'Doplňte alespoň 30 slov textu bez nadpisu.', choose: 'Jazyk není jednoznačný. Vyberte ho u textu.', error: 'Text se nepodařilo změřit. Zkuste ho vložit znovu.', done: 'Měření hotovo.', truncated: 'Měříme jen prvních 5 000 slov textu bez nadpisu.',
    copy: 'Kopírovat zprávu', copied: 'Zpráva zkopírována.', fallback: 'Schránka není dostupná. Označenou zprávu zkopírujte pomocí Ctrl+C nebo nabídky telefonu.', close: 'Zavřít', report: 'Zpráva z měření',
    provenance: 'Příklad od Claude (Anthropic), 29. 9. 2026, česká adaptace Astra. Ukázka stylu, nikoli kalibrační vzorek nebo věcná rada.',
    about: 'Jak číst výsledek', aboutText: 'Začněte zvýrazněným místem. Rada je podnět k vlastní úpravě, ne povinnost odstranit každou frázi. Od 30 do 79 slov měříme jen fráze, pomlčky, nominalizace a trojice. Stejný text, jazyk a verze dávají stejné výsledky.',
    future: 'Přepis vaším hlasem, profil a porovnání verzí připravujeme. Teď je dostupné měření bez účtu a bez placení.',
    faq: 'Časté otázky', watermark: 'Odstraní Rukopis vodoznak Claude?', watermarkText: 'Ne. Rukopis vodoznak Claude neověřuje ani neodstraňuje. Neslibuje obcházení kontrol. Pomáhá upravit styl vlastními slovy.',
    author: 'Dokáže číslo určit autora?', authorText: 'Ne. I člověk používá šablonovité fráze. Index je orientační pomůcka k úpravě stylu, nikoli důkaz původu textu.',
    languages: 'Ve kterých jazycích měření funguje?', languagesText: 'Ve slovenštině, češtině, angličtině a němčině. Automatický odhad můžete kdykoli změnit. U krátkého nebo smíšeného textu vyberte jazyk ručně.',
    data: 'Co se děje s textem?', dataText: 'Zpracovává se jen v tomto prohlížeči. Neukládáme ho do historie ani neposíláme na server. Anonymní událost obsahuje jen jazyk, pásmo výsledku a velikostní kategorii. Zprávu kopírujete pouze vlastním tlačítkem.',
    sources: 'Podklady a omezení', sourcesText: 'StoryScope, Reinhart et al. a LAMP jsou podklady pro pracovní hypotézy, ne kalibrace našeho indexu. Trojice jsou vlastní hypotéza. Shoda s frází neurčuje autorství.',
    metrics: ['Rytmus vět','Rovnoměrnost odstavců','Pointa na konci','Odbočky a konkrétnosti','Otevřenost','Šablonovité fráze','Pomlčky','Nominalizace','Trojice'],
    types: ['fráze','pointa','trojice','nominalizace','pomlčky','konkrétnosti','otevřenost'],
    advice: [
      ['Podobné délky vět mohou působit jednotvárně.','Zkraťte jednu větu tak, aby zůstala její hlavní myšlenka.'],
      ['Stejně dlouhé odstavce mohou zakrýt rozdíly mezi myšlenkami.','Oddělte nový argument do samostatného odstavce.'],
      ['Závěrečné poučení může opakovat to, co čtenář už pochopil.','Vymažte závěrečnou radu, pokud nepřidává novou informaci.'],
      ['Málo konkrétních údajů může znít obecně; samotné jméno nic nedokazuje.','Přidejte jeden doložitelný příklad z vaší firmy.'],
      ['Text neukazuje mnoho otázek ani nejistoty. To samo o sobě není chyba.','Pokud něco nevíte, pojmenujte přesně, co to je.'],
      ['Tato formulace je v našem seznamu často opakovaných frází.','Nahraďte ji jedním konkrétním příkladem z vaší firmy.'],
      ['Časté pomlčky mohou vytvářet opakující se rytmus.','Zkuste zde tečku a dvě kratší věty.'],
      ['Přípona naznačuje abstraktní podstatné jméno, ne vždy správně.','Pojmenujte člověka a sloveso: kdo přesně co udělal?'],
      ['Tříčlenný výčet může znít naučeně. Jde o pracovní hypotézu.','Nechte nejdůležitější bod a doložte ho příkladem.']
    ]
  },
  de: {
    autoShort: "Automatisch",
    rhythmEven: "Die Sätze sind ähnlich lang, was eintönig wirken kann.",
    rhythmVaried: "Die Satzlängen wechseln, der Rhythmus ist abwechslungsreicher.",
    rhythmFew: "Zur Bewertung des Rhythmus sind mindestens 80 Wörter und 5 Sätze nötig.",
    rhythmHint: "Tippen Sie auf einen Balken oder wählen Sie ihn mit Tab. Das Diagramm lässt sich scrollen.",
    average: "Durchschnitt",
    uniform: "Gleichmäßig",
    sentence: "Satz",
    title: 'Rukopis: Floskeln im eigenen Text erkennen', heading: 'Weniger Floskeln. Mehr eigene Stimme.', lead: 'Sehen Sie, wo Ihr Text vage bleibt und welche Stelle Sie zuerst überarbeiten können.',
    badge: 'Rukopis · kostenloser Textcheck', tool: 'Textcheck', example: 'Beispiel', own: 'Eigenen Text einsetzen', undo: 'Text zurückholen', load: 'Beispiel laden',
    measure: 'Text kostenlos prüfen', label: 'Text zur Prüfung', language: 'Textsprache', auto: 'Automatisch erkennen', detected: 'Erkannte Sprache', selected: 'Gewählte Sprache',
    privacy: 'Ihr Text bleibt im Browser.', free: '0 € Textcheck, ohne Konto', index: 'Glätteindex', bands: ['lebendig','gemischt','zu glatt'], partial: 'Teilwert',
    calibration: 'Vorläufige Schwellenwerte, noch nicht kalibriert.', meaning: 'Die Zahl beschreibt den Stil, nicht die Urheberschaft. Höhere Werte bedeuten mehr schematische Merkmale.',
    words: 'Wörter', sentences: 'Sätze', version: 'Version', rhythm: 'Satzlängen in Wörtern', numbers: 'Diagrammwerte', findings: 'Fundstellen im Text', hint: 'Tippen Sie auf eine markierte Stelle oder wählen Sie sie mit Tab aus.', first: 'Hier können Sie anfangen', jump: 'Erste Fundstelle', details: 'Messwerte im Detail', unmeasured: 'Nicht gemessen: benötigt 80 Wörter, für den Rhythmus 5 Sätze und für Absatzlängen 3 Absätze.',
    nofindings: 'Keine Fundstellen zum Markieren. Prüfen Sie trotzdem, ob der Text etwas Konkretes sagt.', low: 'Ergänzen Sie mindestens 30 Wörter im Textkörper, ohne Überschrift.', choose: 'Die Sprache ist nicht eindeutig. Wählen Sie sie neben dem Text aus.', error: 'Der Text konnte nicht geprüft werden. Bitte erneut einfügen.', done: 'Prüfung abgeschlossen.', truncated: 'Nur die ersten 5.000 Wörter im Textkörper werden gemessen.',
    copy: 'Bericht kopieren', copied: 'Bericht kopiert.', fallback: 'Kein Zugriff auf die Zwischenablage. Kopieren Sie den markierten Bericht mit Strg+C oder über das Auswahlmenü Ihres Telefons.', close: 'Schließen', report: 'Textbericht',
    provenance: 'Beispiel von Claude (Anthropic), 29. September 2026, deutsche Bearbeitung von Astra. Stilbeispiel, keine Kalibrierungsprobe oder Sachberatung.',
    about: 'So lesen Sie das Ergebnis', aboutText: 'Beginnen Sie bei einer markierten Stelle. Die Hinweise regen zur Überarbeitung an; Sie müssen nicht jede Formulierung streichen. Bei 30 bis 79 Wörtern prüfen wir nur Floskeln, Gedankenstriche, Nominalisierungen und Dreierlisten. Derselbe Text liefert bei gleicher Sprache und Version dieselben Werte.',
    future: 'Stimmprofile, Überarbeitungen und Versionsvergleiche sind in Vorbereitung. Der Textcheck ist jetzt ohne Konto und Zahlung verfügbar.',
    faq: 'Fragen zum Textcheck', watermark: 'Entfernt Rukopis das Wasserzeichen von Claude?', watermarkText: 'Nein. Rukopis prüft oder entfernt das Wasserzeichen von Claude nicht und verspricht keine Umgehung von Kontrollen. Es hilft Ihnen, den Stil mit eigenen Worten zu überarbeiten.',
    author: 'Kann die Zahl den Autor bestimmen?', authorText: 'Nein. Auch Menschen schreiben in Floskeln. Der Index ist eine vorläufige Schreibhilfe, kein Beleg für die Herkunft eines Textes.',
    languages: 'Welche Sprachen werden unterstützt?', languagesText: 'Slowakisch, Tschechisch, Englisch und Deutsch. Die automatische Erkennung lässt sich jederzeit ändern. Wählen Sie bei kurzen oder gemischtsprachigen Texten die Sprache selbst.',
    data: 'Was passiert mit meinem Text?', dataText: 'Er wird ausschließlich in diesem Browser verarbeitet, weder gespeichert noch an einen Server gesendet. Anonyme Nutzungsereignisse enthalten nur Sprache, Ergebnisbereich und Längenkategorie. Der Bericht wird nur auf Ihren Klick kopiert.',
    sources: 'Grundlagen und Grenzen', sourcesText: 'StoryScope, Reinhart et al. und LAMP liefern Anhaltspunkte für Arbeitshypothesen, keine Kalibrierung unseres Index. Dreierlisten sind eine eigene Hypothese. Ein Floskelfund belegt keine Urheberschaft.',
    metrics: ['Satzrhythmus','Gleichmäßige Absätze','Abschließende Botschaft','Einschübe und konkrete Angaben','Offenheit','Floskeln','Gedankenstriche','Nominalisierungen','Dreierlisten'],
    types: ['Floskeln','Schlussbotschaft','Dreierlisten','Nominalisierungen','Gedankenstriche','konkrete Angaben','Offenheit'],
    advice: [
      ['Ähnliche Satzlängen können eintönig wirken.','Kürzen Sie einen Satz, ohne seine Kernaussage zu verlieren.'],
      ['Gleich lange Absätze können Gedankenwechsel verdecken.','Beginnen Sie für ein neues Argument einen eigenen Absatz.'],
      ['Eine Schlussbotschaft kann bereits Verstandenes wiederholen.','Streichen Sie den letzten Rat, wenn er nichts Neues hinzufügt.'],
      ['Wenige konkrete Angaben können vage wirken; ein Name allein belegt nichts.','Ergänzen Sie ein belegbares Beispiel aus Ihrem Unternehmen.'],
      ['Der Text enthält wenige Fragen oder Unsicherheiten. Das ist nicht automatisch falsch.','Benennen Sie eine tatsächliche offene Frage möglichst genau.'],
      ['Diese Formulierung steht auf unserer Liste häufig wiederholter Wendungen.','Ersetzen Sie sie durch ein konkretes Beispiel aus Ihrem Unternehmen.'],
      ['Viele Gedankenstriche können einen gleichförmigen Rhythmus erzeugen.','Versuchen Sie hier einen Punkt und zwei kürzere Sätze.'],
      ['Die Endung deutet auf ein abstraktes Substantiv hin; das kann falsch sein.','Nennen Sie Person und Handlung: Wer hat was getan?'],
      ['Dreierlisten können einstudiert klingen. Das ist eine Arbeitshypothese.','Behalten Sie den stärksten Punkt und belegen Sie ihn mit einem Beispiel.']
    ]
  }
};
