export const jazyky = { sk: 'Slovenčina', cs: 'Čeština', en: 'English', de: 'Deutsch' };
export const cesta = j => '/rukopis/' + (j === 'sk' ? '' : j + '/');
export const texty = {
  sk: {
    autoShort: "Automaticky",
    rhythmEven: "Vety majú podobnú dĺžku, text môže znieť monotónne.",
    rhythmVaried: "Dĺžka viet sa mení, rytmus je pestrejší.",
    rhythmFew: "Na hodnotenie rytmu treba aspoň 80 slov a 5 viet.",
    rhythmHint: "Ťuknite na stĺpec alebo ho vyberte klávesom Tab. Graf možno posúvať.",
    average: "Priemer",
    uniform: "Rovnomerné",
    sentence: "Veta",
    title: 'Rukopis: nájdite šablónové frázy vo svojom texte',
    heading: 'Menej fráz. Viac vášho hlasu.',
    lead: 'Zistite, kde text znie všeobecne a čo upraviť ako prvé.',
    badge: 'Rukopis · bezplatné meranie', tool: 'Meranie textu', example: 'Príklad', own: 'Vložiť vlastný text', undo: 'Vrátiť text', load: 'Načítať príklad',
    measure: 'Zmerať text zadarmo', label: 'Text na meranie', language: 'Jazyk textu', auto: 'Rozpoznať automaticky', detected: 'Rozpoznaný jazyk', selected: 'Zvolený jazyk',
    privacy: 'Text ostáva v prehliadači.', free: '0 € meranie, bez registrácie', index: 'Šablónovosť textu',
    bands: ['živý', 'zmiešaný', 'šablónový'], partial: 'čiastočný index',
    calibration: 'Orientačné prahy, zatiaľ nekalibrované.', meaning: 'Vyššie číslo znamená viac šablónových znakov v texte. Nehovorí, kto text napísal.',
    words: 'slov', sentences: 'viet', version: 'verzia', rhythm: 'Dĺžky viet v slovách', numbers: 'Číselné hodnoty grafu',
    findings: 'Nálezy v texte', hint: 'Ťuknite na zvýraznené miesto alebo naň prejdite klávesom Tab.', first: 'Čo opraviť najprv', jump: 'Ukázať v texte',
    details: 'Podrobné merania', unmeasured: 'Nemerané: treba 80 slov, pri rytme 5 viet a pri odsekoch 3 odseky.',
    nofindings: 'Žiadne nálezy na zvýraznenie. Skontrolujte ešte, či text hovorí niečo konkrétne.',
    low: 'Doplňte aspoň 30 slov tela bez nadpisu.', choose: 'Jazyk nie je jednoznačný. Vyberte ho pri texte.', error: 'Meranie sa nepodarilo. Skúste text vložiť znova.',
    done: 'Meranie hotové.', truncated: 'Meriame iba prvých 5 000 slov tela.',
    copy: 'Kopírovať správu', download: 'Stiahnuť správu', downloaded: 'Správa stiahnutá.', reportTitle: 'Správa Rukopisu', reportIntro: 'Meranie štýlu textu. Nie je to detektor AI ani posudok autorstva.', reportText: 'Váš text so zvýraznenými miestami', reportDate: 'Zmerané', reportPrivacy: 'Text neopustil váš prehliadač. Túto správu vytvoril prehliadač vo vašom počítači.', reportFile: 'rukopis-sprava', legend: 'Farby vo vašom texte', copied: 'Správa skopírovaná.', fallback: 'Schránka nie je dostupná. Označenú správu skopírujte cez Ctrl+C alebo ponuku telefónu.', close: 'Zavrieť', report: 'Správa z merania',
    provenance: 'Príklad od Claude (Anthropic), 29. 9. 2026. Ilustrácia štýlu, nie kalibračná vzorka ani vecná rada.',
    about: 'Ako čítať výsledok', aboutText: 'Začnite zvýrazneným miestom. Rada je podnet na vlastnú úpravu, nie povinnosť odstrániť každú frázu. Od 30 do 79 slov meriame len šablónové frázy, dlhé pomlčky, podstatné mená namiesto slovies a vymenovania po troch. Rovnaký text, jazyk a verzia dávajú rovnaké výsledky.',
    future: 'Prepis vaším hlasom, profil a porovnanie verzií pripravujeme. Teraz je dostupné meranie, bez účtu a bez platby.',
    faq: 'Časté otázky', watermark: 'Odstráni Rukopis vodoznak Claude?', watermarkText: 'Nie. Rukopis vodoznak Claude neoveruje ani neodstraňuje. Nesľubuje obchádzanie kontrol. Pomáha upraviť štýl vlastnými slovami.',
    author: 'Dokáže číslo určiť autora?', authorText: 'Nie. Aj človek používa šablónové frázy. Index je orientačná pomôcka na úpravu štýlu, nie dôkaz pôvodu textu.',
    languages: 'Ktoré jazyky sa merajú?', languagesText: 'Slovenčina, čeština, angličtina a nemčina. Automatický odhad môžete vždy zmeniť. Pri krátkom alebo zmiešanom texte vyberte jazyk ručne.',
    data: 'Čo sa deje s textom?', dataText: 'Spracúva sa len v tomto prehliadači. Neukladáme ho do histórie ani neposielame na server. Anonymné meranie použitia obsahuje iba jazyk, pásmo a veľkostné vedro. Správu kopírujete len svojím tlačidlom.',
    sources: 'Podklady a hranice', sourcesText: 'StoryScope, Reinhart et al. a LAMP sú podklady pre pracovné hypotézy, nie kalibrácia nášho indexu. Vymenovania po troch sú vlastná hypotéza. Zhoda s frázou neurčuje autorstvo.',
    metrics: ['Rovnaká dĺžka viet','Rovnako dlhé odseky','Poučenie na konci','Konkrétne údaje','Otázky a priznaná neistota','Šablónové frázy','Dlhé pomlčky','Podstatné mená namiesto slovies','Vymenovania po troch'],
    types: ['Šablónové frázy','Poučenie na konci','Vymenovania po troch','Podstatné mená namiesto slovies','Dlhé pomlčky','Konkrétne údaje','Otázky a priznaná neistota'],
    // [čo to je, čo s tým]. Obyčajná reč pre človeka, nie pre lingvistu.
    advice: [
      ['Keď majú vety takmer rovnakú dĺžku, text znie ako odrecitovaný.','Jednu dlhú vetu rozdeľte alebo dve krátke spojte, aby sa dĺžky striedali.'],
      ['Odseky majú skoro rovnaký počet slov, takže text pôsobí ako vyplnený formulár.','Dôležitej myšlienke dajte dlhší odsek, vedľajšej kratší.'],
      ['Posledná veta radí alebo zhŕňa to, čo čitateľ už vie, napríklad „Na záver“ alebo „Nezabúdajte“.','Záverečné poučenie vymažte alebo ho nahraďte konkrétnym ďalším krokom.'],
      ['Čísla, mená, citácie a poznámky v zátvorke. Ukazujú, že autor vie, o čom píše, a sú v poriadku.','Nič netreba meniť. Ak je ich v texte málo, doplňte číslo alebo príklad, ktorý viete doložiť.'],
      ['Otázka alebo priznanie, že niečo neviete. Robí text ľudskejším; keď chýba, nie je to chyba.','Nič netreba meniť. Ak niečo ešte neviete, napíšte to priamo.'],
      ['Ustálené spojenia, ktoré sa opakujú v tisíckach textov, napríklad „v dnešnej dobe“ alebo „kľúčová úloha“.','Frázu vymažte alebo ju nahraďte konkrétnym faktom z vašej témy.'],
      ['Dlhá pomlčka uprostred vety namiesto čiarky alebo bodky. V slovenskom texte jej časté použitie pôsobí cudzo.','Pomlčku nahraďte čiarkou alebo vetu rozdeľte bodkou.'],
      ['Slová končiace na -anie, -enie, -cia alebo -osť, napríklad „zabezpečenie“, „realizácia“, „efektívnosť“. Skrývajú, kto čo robí, a vety s nimi ťažknú. Obyčajné slová ako „veľkosť“ sa počítajú tiež, tie sú v poriadku.','Ak veta znie ťažko, povedzte to slovesom: namiesto „vykonanie kontroly“ napíšte „skontrolujeme“. Inak nechajte.'],
      ['Tri veci za sebou, napríklad „rýchlosť, presnosť a prehľadnosť“. Keď sa to opakuje v každom odseku, text znie naučene.','Ak ide o skutočné veci (múka, droždie, soľ), nechajte to tak. Ak sú to nejasné slová, nechajte najdôležitejšie a doložte ho príkladom.']
    ],
    rhythmTitle: 'Dĺžka viet',
    rhythmExplain: 'Každý stĺpec je jedna veta, jeho výška je počet slov. Keď sú stĺpce rovnako vysoké, text znie monotónne.',
    rhythmExplainHist: 'Text má {n}, preto ich zoskupujeme podľa dĺžky. Stĺpec ukazuje, koľko viet má daný počet slov. Keď je väčšina viet v jednom stĺpci, text znie monotónne.',
    rhythmHintHist: 'Ťuknite na stĺpec alebo ho vyberte klávesom Tab.',
    binRange: 'od {a} do {b} slov', binLast: 'aspoň {a} slov',
    wordForms: {one:'slovo',few:'slová',many:'slova',other:'slov'}, sentenceForms: {one:'veta',few:'vety',many:'vety',other:'viet'},
    hitForms: {one:'výskyt',few:'výskyty',many:'výskytu',other:'výskytov'}, lineForms: {one:'riadok',few:'riadky',many:'riadka',other:'riadkov'},
    perHundred: '{n} na 100 slov', inText: 'Prvý výskyt vo vašom texte', todo: 'Čo s tým',
    firstLead: 'Zoradené podľa toho, koľko pridávajú k indexu. Každý nález je podnet na úpravu, nie chyba.',
    explainLink: 'Čo jednotlivé nálezy znamenajú a čo s nimi',
    skipped: 'Vynechali sme {n}.', skippedWhy: 'Nie sú súvislý text; takéto riadky vzniknú pri kopírovaní z PDF alebo Wordu. V texte nižšie sú prečiarknuté.',
    reasons: {obsah:'riadky obsahu s číslom strany',strana:'čísla strán a opakované záhlavia',titul:'titulná strana (škola, fakulta, evidenčné číslo)',nadpis:'nadpisy kapitol',vzorec:'vzorce a riadky zo samých čísel'},
    glued: 'Rozdelili sme aj zlepené slová ({n}), napríklad „{w}“.',
    pdf: 'Môžem vložiť text z PDF alebo Wordu?', pdfText: 'Áno. Riadky obsahu, čísla strán, titulnú stranu, číslované nadpisy a vzorce z merania vynecháme a pri výsledku povieme, koľko riadkov to bolo. Slová zlepené na konci strany rozdelíme, ak je to jednoznačné.'
  },
  en: {
    autoShort: "Automatic",
    rhythmEven: "Sentence lengths are similar, which can sound monotonous.",
    rhythmVaried: "Sentence lengths vary, giving the text a more varied rhythm.",
    rhythmFew: "Rhythm needs at least 80 words and 5 sentences to be assessed.",
    rhythmHint: "Tap a bar or use Tab to select it. The chart can scroll.",
    average: "Average",
    uniform: "Uniform",
    sentence: "Sentence",
    title: 'Rukopis: find stock phrases in your writing', heading: 'Less stock phrasing. More of you.', lead: 'See where your writing gets vague, and where to start editing.',
    badge: 'Rukopis · free writing check', tool: 'Writing check', example: 'Example', own: 'Use my own text', undo: 'Restore text', load: 'Load example',
    measure: 'Check my writing', label: 'Text to check', language: 'Text language', auto: 'Detect automatically', detected: 'Detected language', selected: 'Selected language',
    privacy: 'Your text stays in your browser.', free: '€0 to check, no account', index: 'Template score', bands: ['lively','mixed','template-like'], partial: 'partial score',
    calibration: 'Provisional thresholds, not yet calibrated.', meaning: 'This describes style, not authorship. Higher scores mean more formulaic features.',
    words: 'words', sentences: 'sentences', version: 'version', rhythm: 'Sentence lengths in words', numbers: 'Chart values', findings: 'Inside your text', hint: 'Tap a highlighted passage or reach it with Tab.', first: 'Where to start', jump: 'Show in text', details: 'Detailed measurements', unmeasured: 'Not measured: needs 80 words, 5 sentences for rhythm and 3 paragraphs for paragraph length.',
    nofindings: 'No passages to highlight. Still check whether your text says something specific.', low: 'Add at least 30 body words, excluding the heading.', choose: 'The language is unclear. Choose it next to your text.', error: 'Could not check the text. Please paste it again.', done: 'Check complete.', truncated: 'Only the first 5,000 body words are measured.',
    copy: 'Copy report', download: 'Download report', downloaded: 'Report downloaded.', reportTitle: 'Rukopis report', reportIntro: 'A measurement of writing style. It is not an AI detector and does not judge who wrote the text.', reportText: 'Your text with the marked places', reportDate: 'Measured', reportPrivacy: 'Your text never left your browser. Your browser made this report on your computer.', reportFile: 'rukopis-report', legend: 'Colours in your text', copied: 'Report copied.', fallback: 'Clipboard access is unavailable. Copy the selected report with Ctrl+C or your phone’s selection menu.', close: 'Close', report: 'Writing report',
    provenance: 'Example by Claude (Anthropic), 29 September 2026. A style illustration, not a calibration sample or factual advice.',
    about: 'Reading your results', aboutText: 'Start with a highlighted passage. Each suggestion is an editing prompt, not a rule to remove every phrase. Texts of 30 to 79 words receive only the stock phrase, long dash, nouns instead of verbs and lists of three checks. The same text, language and version produce the same result.',
    future: 'Voice profiles, rewriting and version comparisons are in preparation. The writing check is available now, with no account or payment.',
    faq: 'Questions', watermark: 'Does Rukopis remove Claude’s watermark?', watermarkText: 'No. Rukopis neither verifies nor removes Claude’s watermark. It does not promise to bypass checks. It helps you revise the style in your own words.',
    author: 'Can a score identify the author?', authorText: 'No. People use stock phrases too. The index is a provisional editing aid, not evidence of where a text came from.',
    languages: 'Which languages can I check?', languagesText: 'Slovak, Czech, English and German. You can override automatic detection at any time. Choose manually for short or mixed-language writing.',
    data: 'What happens to my text?', dataText: 'It is processed only in this browser. We do not save it to a history or send it to a server. Anonymous usage events contain only language, score band and length bucket. Copying a report requires your click.',
    sources: 'Evidence and limits', sourcesText: 'StoryScope, Reinhart et al. and LAMP inform working hypotheses; they do not validate our index. Lists of three are our own hypothesis. A phrase match says nothing about authorship.',
    metrics: ['Same-length sentences','Same-length paragraphs','Moral at the end','Specific details','Questions and admitted doubt','Stock phrases','Long dashes','Nouns instead of verbs','Lists of three'],
    types: ['Stock phrases','Moral at the end','Lists of three','Nouns instead of verbs','Long dashes','Specific details','Questions and admitted doubt'],
    advice: [
      ['When sentences are nearly the same length, the text sounds recited.','Split one long sentence or join two short ones so the lengths vary.'],
      ['Paragraphs have almost the same word count, so the text reads like a filled-in form.','Give an important idea a longer paragraph and a side note a shorter one.'],
      ['The last sentence gives advice or repeats what the reader already knows, such as “Ultimately” or “Remember”.','Delete the closing lesson or replace it with one concrete next step.'],
      ['Numbers, names, quotes and notes in brackets. They show the author knows the subject, and they are fine.','Nothing to change. If there are few of them, add a number or an example you can back up.'],
      ['A question or an admission that you do not know something. It makes writing more human; its absence is not an error.','Nothing to change. If something is still unclear to you, say so plainly.'],
      ['Set phrases repeated in thousands of texts, such as “in today’s fast-paced world” or “plays a crucial role”.','Delete the phrase or replace it with a concrete fact from your topic.'],
      ['A long dash in the middle of a sentence instead of a comma or full stop. Frequent dashes create a repetitive rhythm.','Replace the dash with a comma, or split the sentence with a full stop.'],
      ['Long abstract words ending in -tion, -ment, -ness or -ity, such as “implementation”, “optimisation” or “effectiveness”. They hide who does what and make sentences heavy. Plain words that share an ending are counted too and are fine.','If a sentence reads heavy, say it with a verb: instead of “carry out an assessment”, write “we assess”. Otherwise leave it.'],
      ['Three items in a row, such as “speed, accuracy and transparency”. When it happens in every paragraph, the text sounds rehearsed.','If they are real things (flour, yeast, salt), leave it. If they are vague words, keep the most important one and support it with an example.']
    ],
    rhythmTitle: 'Sentence length',
    rhythmExplain: 'Each bar is one sentence and its height is the number of words. When the bars are all the same height, the text sounds monotonous.',
    rhythmExplainHist: 'The text has {n}, so we group them by length. Each bar shows how many sentences have that many words. When most sentences sit in one bar, the text sounds monotonous.',
    rhythmHintHist: 'Tap a bar or use Tab to select it.',
    binRange: 'from {a} to {b} words', binLast: '{a} words or more',
    wordForms: {one:'word',other:'words'}, sentenceForms: {one:'sentence',other:'sentences'},
    hitForms: {one:'occurrence',other:'occurrences'}, lineForms: {one:'line',other:'lines'},
    perHundred: '{n} per 100 words', inText: 'First occurrence in your text', todo: 'What to do',
    firstLead: 'Sorted by how much each one adds to the index. Every finding is a prompt to edit, not an error.',
    explainLink: 'What each finding means and what to do',
    skipped: 'We skipped {n}.', skippedWhy: 'They are not running text; lines like these appear when you copy from a PDF or Word file. They are struck through in the text below.',
    reasons: {obsah:'table of contents lines with page numbers',strana:'page numbers and repeated headers',titul:'title page (school, faculty, registration number)',nadpis:'chapter headings',vzorec:'formulas and number-only lines'},
    glued: 'We also split words that were stuck together ({n}), for example “{w}”.',
    pdf: 'Can I paste text from a PDF or Word file?', pdfText: 'Yes. Table of contents lines, page numbers, the title page, numbered headings and formulas are left out of the check, and the result tells you how many lines that was. Words stuck together at a page break are split when it is unambiguous.'
  },
  cs: {
    autoShort: "Automaticky",
    rhythmEven: "Věty mají podobnou délku, text může znít jednotvárně.",
    rhythmVaried: "Délka vět se mění, rytmus je pestřejší.",
    rhythmFew: "Pro hodnocení rytmu je třeba alespoň 80 slov a 5 vět.",
    rhythmHint: "Klepněte na sloupec nebo jej vyberte klávesou Tab. Graf lze posouvat.",
    average: "Průměr",
    uniform: "Rovnoměrné",
    sentence: "Věta",
    title: 'Rukopis: najděte šablonovité fráze ve svém textu', heading: 'Méně frází. Více vašeho hlasu.', lead: 'Podívejte se, kde text zní obecně a co upravit jako první.',
    badge: 'Rukopis · měření zdarma', tool: 'Měření textu', example: 'Příklad', own: 'Vložit vlastní text', undo: 'Vrátit text', load: 'Načíst příklad',
    measure: 'Změřit text zdarma', label: 'Text k měření', language: 'Jazyk textu', auto: 'Rozpoznat automaticky', detected: 'Rozpoznaný jazyk', selected: 'Zvolený jazyk',
    privacy: 'Text zůstává v prohlížeči.', free: '0 € měření, bez registrace', index: 'Šablonovitost textu', bands: ['živý','smíšený','šablonovitý'], partial: 'částečný index',
    calibration: 'Orientační prahy, zatím nekalibrované.', meaning: 'Číslo popisuje styl, neurčuje autora. Vyšší číslo znamená více šablonovitých znaků.',
    words: 'slov', sentences: 'vět', version: 'verze', rhythm: 'Délky vět ve slovech', numbers: 'Číselné hodnoty grafu', findings: 'Nálezy v textu', hint: 'Klepněte na zvýrazněné místo nebo na ně přejděte klávesou Tab.', first: 'Co upravit nejdřív', jump: 'Ukázat v textu', details: 'Podrobná měření', unmeasured: 'Neměřeno: je třeba 80 slov, pro rytmus 5 vět a pro odstavce 3 odstavce.',
    nofindings: 'Žádné nálezy ke zvýraznění. Ještě ověřte, zda text říká něco konkrétního.', low: 'Doplňte alespoň 30 slov textu bez nadpisu.', choose: 'Jazyk není jednoznačný. Vyberte ho u textu.', error: 'Text se nepodařilo změřit. Zkuste ho vložit znovu.', done: 'Měření hotovo.', truncated: 'Měříme jen prvních 5 000 slov textu bez nadpisu.',
    copy: 'Kopírovat zprávu', download: 'Stáhnout zprávu', downloaded: 'Zpráva stažena.', reportTitle: 'Zpráva Rukopisu', reportIntro: 'Měření stylu textu. Není to detektor AI ani posudek autorství.', reportText: 'Váš text se zvýrazněnými místy', reportDate: 'Změřeno', reportPrivacy: 'Text neopustil váš prohlížeč. Tuto zprávu vytvořil prohlížeč ve vašem počítači.', reportFile: 'rukopis-zprava', legend: 'Barvy ve vašem textu', copied: 'Zpráva zkopírována.', fallback: 'Schránka není dostupná. Označenou zprávu zkopírujte pomocí Ctrl+C nebo nabídky telefonu.', close: 'Zavřít', report: 'Zpráva z měření',
    provenance: 'Příklad od Claude (Anthropic), 29. 9. 2026, česká adaptace Astra. Ukázka stylu, nikoli kalibrační vzorek nebo věcná rada.',
    about: 'Jak číst výsledek', aboutText: 'Začněte zvýrazněným místem. Rada je podnět k vlastní úpravě, ne povinnost odstranit každou frázi. Od 30 do 79 slov měříme jen šablonovité fráze, dlouhé pomlčky, podstatná jména místo sloves a výčty po třech. Stejný text, jazyk a verze dávají stejné výsledky.',
    future: 'Přepis vaším hlasem, profil a porovnání verzí připravujeme. Teď je dostupné měření bez účtu a bez placení.',
    faq: 'Časté otázky', watermark: 'Odstraní Rukopis vodoznak Claude?', watermarkText: 'Ne. Rukopis vodoznak Claude neověřuje ani neodstraňuje. Neslibuje obcházení kontrol. Pomáhá upravit styl vlastními slovy.',
    author: 'Dokáže číslo určit autora?', authorText: 'Ne. I člověk používá šablonovité fráze. Index je orientační pomůcka k úpravě stylu, nikoli důkaz původu textu.',
    languages: 'Ve kterých jazycích měření funguje?', languagesText: 'Ve slovenštině, češtině, angličtině a němčině. Automatický odhad můžete kdykoli změnit. U krátkého nebo smíšeného textu vyberte jazyk ručně.',
    data: 'Co se děje s textem?', dataText: 'Zpracovává se jen v tomto prohlížeči. Neukládáme ho do historie ani neposíláme na server. Anonymní událost obsahuje jen jazyk, pásmo výsledku a velikostní kategorii. Zprávu kopírujete pouze vlastním tlačítkem.',
    sources: 'Podklady a omezení', sourcesText: 'StoryScope, Reinhart et al. a LAMP jsou podklady pro pracovní hypotézy, ne kalibrace našeho indexu. Výčty po třech jsou vlastní hypotéza. Shoda s frází neurčuje autorství.',
    metrics: ['Stejná délka vět','Stejně dlouhé odstavce','Poučení na konci','Konkrétní údaje','Otázky a přiznaná nejistota','Šablonovité fráze','Dlouhé pomlčky','Podstatná jména místo sloves','Výčty po třech'],
    types: ['Šablonovité fráze','Poučení na konci','Výčty po třech','Podstatná jména místo sloves','Dlouhé pomlčky','Konkrétní údaje','Otázky a přiznaná nejistota'],
    advice: [
      ['Když mají věty skoro stejnou délku, text zní jako odříkaný.','Jednu dlouhou větu rozdělte nebo dvě krátké spojte, aby se délky střídaly.'],
      ['Odstavce mají skoro stejný počet slov, takže text působí jako vyplněný formulář.','Důležité myšlence dejte delší odstavec, vedlejší kratší.'],
      ['Poslední věta radí nebo shrnuje to, co čtenář už ví, například „Závěrem“ nebo „Nezapomínejte“.','Závěrečné poučení smažte nebo ho nahraďte konkrétním dalším krokem.'],
      ['Čísla, jména, citace a poznámky v závorce. Ukazují, že autor ví, o čem píše, a jsou v pořádku.','Není třeba nic měnit. Pokud jich je v textu málo, doplňte číslo nebo příklad, který umíte doložit.'],
      ['Otázka nebo přiznání, že něco nevíte. Dělá text lidštějším; když chybí, není to chyba.','Není třeba nic měnit. Pokud něco ještě nevíte, napište to přímo.'],
      ['Ustálená spojení, která se opakují v tisících textů, například „v dnešní době“ nebo „klíčová role“.','Frázi smažte nebo ji nahraďte konkrétním faktem z vašeho tématu.'],
      ['Dlouhá pomlčka uprostřed věty místo čárky nebo tečky. Její časté použití působí v češtině cize.','Pomlčku nahraďte čárkou nebo větu rozdělte tečkou.'],
      ['Slova končící na -ání, -ení, -ace nebo -ost, například „zabezpečení“, „realizace“, „efektivita“. Skrývají, kdo co dělá, a věty s nimi těžknou. Obyčejná slova jako „velikost“ se počítají také, ta jsou v pořádku.','Když věta zní těžce, řekněte to slovesem: místo „provedení kontroly“ napište „zkontrolujeme“. Jinak nechte.'],
      ['Tři věci za sebou, například „rychlost, přesnost a přehlednost“. Když se to opakuje v každém odstavci, text zní naučeně.','Jde-li o skutečné věci (mouka, droždí, sůl), nechte to. Jsou-li to neurčitá slova, nechte nejdůležitější a doložte je příkladem.']
    ],
    rhythmTitle: 'Délka vět',
    rhythmExplain: 'Každý sloupec je jedna věta, jeho výška je počet slov. Když jsou sloupce stejně vysoké, text zní jednotvárně.',
    rhythmExplainHist: 'Text má {n}, proto je seskupujeme podle délky. Sloupec ukazuje, kolik vět má daný počet slov. Když je většina vět v jednom sloupci, text zní jednotvárně.',
    rhythmHintHist: 'Klepněte na sloupec nebo jej vyberte klávesou Tab.',
    binRange: 'od {a} do {b} slov', binLast: 'nejméně {a} slov',
    wordForms: {one:'slovo',few:'slova',many:'slova',other:'slov'}, sentenceForms: {one:'věta',few:'věty',many:'věty',other:'vět'},
    hitForms: {one:'výskyt',few:'výskyty',many:'výskytu',other:'výskytů'}, lineForms: {one:'řádek',few:'řádky',many:'řádku',other:'řádků'},
    perHundred: '{n} na 100 slov', inText: 'První výskyt ve vašem textu', todo: 'Co s tím',
    firstLead: 'Seřazeno podle toho, kolik přidávají k indexu. Každý nález je podnět k úpravě, ne chyba.',
    explainLink: 'Co jednotlivé nálezy znamenají a co s nimi',
    skipped: 'Vynechali jsme {n}.', skippedWhy: 'Nejsou souvislý text; takové řádky vzniknou při kopírování z PDF nebo Wordu. V textu níže jsou přeškrtnuté.',
    reasons: {obsah:'řádky obsahu s číslem strany',strana:'čísla stran a opakovaná záhlaví',titul:'titulní strana (škola, fakulta, evidenční číslo)',nadpis:'nadpisy kapitol',vzorec:'vzorce a řádky ze samých čísel'},
    glued: 'Rozdělili jsme i slepená slova ({n}), například „{w}“.',
    pdf: 'Mohu vložit text z PDF nebo Wordu?', pdfText: 'Ano. Řádky obsahu, čísla stran, titulní stranu, číslované nadpisy a vzorce z měření vynecháme a u výsledku řekneme, kolik řádků to bylo. Slova slepená na konci strany rozdělíme, pokud je to jednoznačné.'
  },
  de: {
    autoShort: "Automatisch",
    rhythmEven: "Die Sätze sind ähnlich lang, was eintönig wirken kann.",
    rhythmVaried: "Die Satzlängen wechseln, der Rhythmus ist abwechslungsreicher.",
    rhythmFew: "Zur Bewertung des Rhythmus sind mindestens 80 Wörter und 5 Sätze nötig.",
    rhythmHint: "Tippen Sie auf einen Balken oder wählen Sie ihn mit Tab. Das Diagramm lässt sich scrollen.",
    average: "Durchschnitt",
    uniform: "Gleichmäßig",
    sentence: "Satz",
    title: 'Rukopis: Floskeln im eigenen Text erkennen', heading: 'Weniger Floskeln. Mehr eigene Stimme.', lead: 'Sehen Sie, wo Ihr Text vage bleibt und welche Stelle Sie zuerst überarbeiten können.',
    badge: 'Rukopis · kostenloser Textcheck', tool: 'Textcheck', example: 'Beispiel', own: 'Eigenen Text einsetzen', undo: 'Text zurückholen', load: 'Beispiel laden',
    measure: 'Text kostenlos prüfen', label: 'Text zur Prüfung', language: 'Textsprache', auto: 'Automatisch erkennen', detected: 'Erkannte Sprache', selected: 'Gewählte Sprache',
    privacy: 'Ihr Text bleibt im Browser.', free: '0 € Textcheck, ohne Konto', index: 'Schablonenwert', bands: ['lebendig','gemischt','schablonenhaft'], partial: 'Teilwert',
    calibration: 'Vorläufige Schwellenwerte, noch nicht kalibriert.', meaning: 'Die Zahl beschreibt den Stil, nicht die Urheberschaft. Höhere Werte bedeuten mehr schematische Merkmale.',
    words: 'Wörter', sentences: 'Sätze', version: 'Version', rhythm: 'Satzlängen in Wörtern', numbers: 'Diagrammwerte', findings: 'Fundstellen im Text', hint: 'Tippen Sie auf eine markierte Stelle oder wählen Sie sie mit Tab aus.', first: 'Hier können Sie anfangen', jump: 'Im Text zeigen', details: 'Messwerte im Detail', unmeasured: 'Nicht gemessen: benötigt 80 Wörter, für den Rhythmus 5 Sätze und für Absatzlängen 3 Absätze.',
    nofindings: 'Keine Fundstellen zum Markieren. Prüfen Sie trotzdem, ob der Text etwas Konkretes sagt.', low: 'Ergänzen Sie mindestens 30 Wörter im Textkörper, ohne Überschrift.', choose: 'Die Sprache ist nicht eindeutig. Wählen Sie sie neben dem Text aus.', error: 'Der Text konnte nicht geprüft werden. Bitte erneut einfügen.', done: 'Prüfung abgeschlossen.', truncated: 'Nur die ersten 5.000 Wörter im Textkörper werden gemessen.',
    copy: 'Bericht kopieren', download: 'Bericht herunterladen', downloaded: 'Bericht heruntergeladen.', reportTitle: 'Rukopis-Bericht', reportIntro: 'Eine Messung des Schreibstils. Kein KI-Detektor und kein Urteil darüber, wer den Text geschrieben hat.', reportText: 'Ihr Text mit den markierten Stellen', reportDate: 'Gemessen', reportPrivacy: 'Ihr Text hat Ihren Browser nie verlassen. Ihr Browser hat diesen Bericht auf Ihrem Computer erstellt.', reportFile: 'rukopis-bericht', legend: 'Farben in Ihrem Text', copied: 'Bericht kopiert.', fallback: 'Kein Zugriff auf die Zwischenablage. Kopieren Sie den markierten Bericht mit Strg+C oder über das Auswahlmenü Ihres Telefons.', close: 'Schließen', report: 'Textbericht',
    provenance: 'Beispiel von Claude (Anthropic), 29. September 2026, deutsche Bearbeitung von Astra. Stilbeispiel, keine Kalibrierungsprobe oder Sachberatung.',
    about: 'So lesen Sie das Ergebnis', aboutText: 'Beginnen Sie bei einer markierten Stelle. Die Hinweise regen zur Überarbeitung an; Sie müssen nicht jede Formulierung streichen. Bei 30 bis 79 Wörtern prüfen wir nur Floskeln, lange Gedankenstriche, Substantive statt Verben und Aufzählungen zu dritt. Derselbe Text liefert bei gleicher Sprache und Version dieselben Werte.',
    future: 'Stimmprofile, Überarbeitungen und Versionsvergleiche sind in Vorbereitung. Der Textcheck ist jetzt ohne Konto und Zahlung verfügbar.',
    faq: 'Fragen zum Textcheck', watermark: 'Entfernt Rukopis das Wasserzeichen von Claude?', watermarkText: 'Nein. Rukopis prüft oder entfernt das Wasserzeichen von Claude nicht und verspricht keine Umgehung von Kontrollen. Es hilft Ihnen, den Stil mit eigenen Worten zu überarbeiten.',
    author: 'Kann die Zahl den Autor bestimmen?', authorText: 'Nein. Auch Menschen schreiben in Floskeln. Der Index ist eine vorläufige Schreibhilfe, kein Beleg für die Herkunft eines Textes.',
    languages: 'Welche Sprachen werden unterstützt?', languagesText: 'Slowakisch, Tschechisch, Englisch und Deutsch. Die automatische Erkennung lässt sich jederzeit ändern. Wählen Sie bei kurzen oder gemischtsprachigen Texten die Sprache selbst.',
    data: 'Was passiert mit meinem Text?', dataText: 'Er wird ausschließlich in diesem Browser verarbeitet, weder gespeichert noch an einen Server gesendet. Anonyme Nutzungsereignisse enthalten nur Sprache, Ergebnisbereich und Längenkategorie. Der Bericht wird nur auf Ihren Klick kopiert.',
    sources: 'Grundlagen und Grenzen', sourcesText: 'StoryScope, Reinhart et al. und LAMP liefern Anhaltspunkte für Arbeitshypothesen, keine Kalibrierung unseres Index. Aufzählungen zu dritt sind eine eigene Hypothese. Ein Floskelfund belegt keine Urheberschaft.',
    metrics: ['Gleich lange Sätze','Gleich lange Absätze','Moral am Schluss','Konkrete Angaben','Fragen und offene Zweifel','Floskeln','Lange Gedankenstriche','Substantive statt Verben','Aufzählungen zu dritt'],
    types: ['Floskeln','Moral am Schluss','Aufzählungen zu dritt','Substantive statt Verben','Lange Gedankenstriche','Konkrete Angaben','Fragen und offene Zweifel'],
    advice: [
      ['Wenn Sätze fast gleich lang sind, klingt der Text wie aufgesagt.','Teilen Sie einen langen Satz oder verbinden Sie zwei kurze, damit die Längen wechseln.'],
      ['Die Absätze haben fast gleich viele Wörter, der Text wirkt wie ein ausgefülltes Formular.','Geben Sie einem wichtigen Gedanken einen längeren Absatz und einem Nebengedanken einen kürzeren.'],
      ['Der letzte Satz gibt einen Rat oder wiederholt Bekanntes, etwa „Fazit“ oder „Denken Sie daran“.','Streichen Sie die Schlussmoral oder ersetzen Sie sie durch einen konkreten nächsten Schritt.'],
      ['Zahlen, Namen, Zitate und Anmerkungen in Klammern. Sie zeigen, dass der Autor das Thema kennt, und sind in Ordnung.','Nichts zu ändern. Wenn es wenige sind, ergänzen Sie eine Zahl oder ein belegbares Beispiel.'],
      ['Eine Frage oder das Eingeständnis, etwas nicht zu wissen. Das macht Texte menschlicher; fehlt es, ist das kein Fehler.','Nichts zu ändern. Wenn etwas noch unklar ist, sagen Sie es direkt.'],
      ['Feste Wendungen, die in Tausenden Texten vorkommen, etwa „in der heutigen Zeit“ oder „eine zentrale Rolle spielen“.','Streichen Sie die Floskel oder ersetzen Sie sie durch eine konkrete Tatsache aus Ihrem Thema.'],
      ['Ein langer Gedankenstrich mitten im Satz statt Komma oder Punkt. Häufig eingesetzt, erzeugt er einen gleichförmigen Rhythmus.','Ersetzen Sie den Strich durch ein Komma oder teilen Sie den Satz mit einem Punkt.'],
      ['Wörter auf -ung, -ion, -keit oder -heit, etwa „Durchführung“, „Optimierung“ oder „Umsetzung“. Sie verbergen, wer was tut, und machen Sätze schwer. Einfache Wörter mit gleicher Endung zählen auch mit und sind in Ordnung.','Wenn ein Satz schwer klingt, sagen Sie es mit einem Verb: statt „die Durchführung einer Prüfung“ schreiben Sie „wir prüfen“. Sonst lassen Sie es.'],
      ['Drei Dinge hintereinander, etwa „Tempo, Präzision und Transparenz“. Passiert das in jedem Absatz, klingt der Text einstudiert.','Sind es echte Dinge (Mehl, Hefe, Salz), lassen Sie es. Sind es vage Wörter, behalten Sie das wichtigste und belegen Sie es mit einem Beispiel.']
    ],
    rhythmTitle: 'Satzlänge',
    rhythmExplain: 'Jeder Balken ist ein Satz, seine Höhe ist die Zahl der Wörter. Sind alle Balken gleich hoch, klingt der Text eintönig.',
    rhythmExplainHist: 'Der Text hat {n}, darum fassen wir sie nach Länge zusammen. Jeder Balken zeigt, wie viele Sätze so viele Wörter haben. Liegen die meisten Sätze in einem Balken, klingt der Text eintönig.',
    rhythmHintHist: 'Tippen Sie auf einen Balken oder wählen Sie ihn mit Tab.',
    binRange: '{a} bis {b} Wörter', binLast: '{a} Wörter oder mehr',
    wordForms: {one:'Wort',other:'Wörter'}, sentenceForms: {one:'Satz',other:'Sätze'},
    hitForms: {one:'Fundstelle',other:'Fundstellen'}, lineForms: {one:'Zeile',other:'Zeilen'},
    perHundred: '{n} pro 100 Wörter', inText: 'Erste Fundstelle in Ihrem Text', todo: 'Was tun',
    firstLead: 'Sortiert danach, wie viel sie zum Index beitragen. Jede Fundstelle ist ein Hinweis, kein Fehler.',
    explainLink: 'Was die Fundstellen bedeuten und was zu tun ist',
    skipped: 'Wir haben {n} ausgelassen.', skippedWhy: 'Sie sind kein Fließtext; solche Zeilen entstehen beim Kopieren aus PDF oder Word. Im Text unten sind sie durchgestrichen.',
    reasons: {obsah:'Inhaltsverzeichnis mit Seitenzahlen',strana:'Seitenzahlen und wiederholte Kopfzeilen',titul:'Titelseite (Hochschule, Fakultät, Matrikelnummer)',nadpis:'Kapitelüberschriften',vzorec:'Formeln und reine Zahlenzeilen'},
    glued: 'Außerdem haben wir zusammengeklebte Wörter getrennt ({n}), zum Beispiel „{w}“.',
    pdf: 'Kann ich Text aus PDF oder Word einfügen?', pdfText: 'Ja. Inhaltsverzeichnis, Seitenzahlen, Titelseite, nummerierte Überschriften und Formeln lassen wir bei der Messung weg und nennen beim Ergebnis die Zahl der Zeilen. Am Seitenende zusammengeklebte Wörter trennen wir, wenn es eindeutig ist.'
  }
};
