import {TEXTY} from './texty.mjs';
import {pripojenie} from './pripojenie.mjs';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base=new URL('./',location.href); base.hash=''; base.search='';
const connection=pripojenie('proof',base);
let publicRegistration=false;
const parts=()=>new URLSearchParams(location.hash.slice(1));
let lang=parts().get('lang')||new URLSearchParams(location.search).get('lang');
if(!lang)try{lang=localStorage.getItem('proof-language');}catch{}
if(!TEXTY[lang])lang='en';
let t=TEXTY[lang], auth=null, jobs=[], jobData=null, reviewData=null, token=parts().get('review')||'', chosenVersion='', filter='all', query='', authMode=new URLSearchParams(location.search).get('start')==='1'?'register':'login', sequence=0, urls=[], noticeTimer, point=null, annotating=false, decisionMode='approved', imageReady=false, conflict=false, reviewerName='', activeLink=null;
const main=$('#main'), modal=$('#modal');
const fmt=value=>{if(!value)return '';const d=new Date(value);return Number.isNaN(d.valueOf())?'':new Intl.DateTimeFormat(lang,{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(d)+' UTC';};
const status=s=>`<span class="status ${['draft','pending','approved','changes_requested'].includes(s)?s:'draft'}">${esc(t[s]||s)}</span>`;
const button=(text,action,cls='')=>`<button type="button" class="btn ${cls}" data-action="${action}">${esc(text)}</button>`;
const field=(label,name,{type='text',value='',required=true,max=160,min='',step='',help='',autocomplete='off'}={})=>`<div class="field"><label for="f-${name}">${esc(label)}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='number'?`max="${max}" min="${min}" step="${step||'1'}"`:`maxlength="${max}"`} autocomplete="${autocomplete}">${help?`<p class="help">${esc(help)}</p>`:''}</div>`;
const area=(label,name,value='',max=2000,required=false)=>`<div class="field"><label for="f-${name}">${esc(label)}</label><textarea id="f-${name}" name="${name}" maxlength="${max}" ${required?'required':''}>${esc(value)}</textarea></div>`;
const formError=form=>{let e=$('.error',form);if(!e){e=document.createElement('p');e.className='error';e.setAttribute('role','alert');form.append(e);}return e;};
function notify(message){const n=$('#notice');n.textContent=message;n.hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.hidden=true,6500);}
function message(error){if(['version_conflict','already_decided'].includes(error.code))return t.stale;if(error.code==='link_unavailable')return t.unavailable;if(error.status===401)return t.sessionExpired;return error.userMessage||error.message||t.error;}
async function api(path,{method='GET',body,review=false,raw=false,headers={}}={}){
  const h={...headers};if(review)h['X-Proof-Token']=token;else if(method!=='GET'&&auth?.csrfToken)h['X-CSRF-Token']=auth.csrfToken;
  if(body!==undefined&&!raw)h['Content-Type']='application/json';
  let res;try{res=await connection.request(path,{method,headers:h,body:body===undefined?undefined:raw?body:JSON.stringify(body)},review);}catch{const e=new Error(t.network);e.userMessage=t.network;throw e;}
  if(!res.ok){let data;try{data=await res.json();}catch{}const e=new Error(data?.error?.message||t.error);e.status=res.status;e.code=data?.error?.code;throw e;}
  return res;
}
const json=async(path,...args)=>{const value=await(await api(path,...args)).json();return /^auth\/(login|register)$/.test(path)?connection.remember(value):value;};
function releaseImages(){for(const u of urls)URL.revokeObjectURL(u);urls=[];}
function replace(html){releaseImages();main.innerHTML=html;main.removeAttribute('aria-busy');imageReady=false;}
function loading(){main.setAttribute('aria-busy','true');}
function header(){
  t=TEXTY[lang];document.documentElement.lang=lang;document.title='ARLing Proof';$('#footer-note').textContent=t.footer;$('#privacy-link').textContent=t.privacy;$('#privacy-link').href='https://arling.sk/proof/'+(lang==='sk'?'sk/':lang==='de'?'de/':'')+'#privacy';
  $('#logout').textContent=t.logout;$('#logout').hidden=!auth||!!token;$('#language').setAttribute('aria-label',t.language);$('#modal-close').setAttribute('aria-label',t.close);
  for(const opt of $('#language').options)opt.hidden=!token&&!['en','sk'].includes(opt.value);
  if(!token&&!['en','sk'].includes(lang)){lang='en';t=TEXTY.en;document.documentElement.lang=lang;}
  $('#language').value=lang;
}
function dialog(title,html){$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;modal.showModal();}
async function submit(form,work){
  if(!form.reportValidity())return;const buttons=$$('button[type=submit]',form);buttons.forEach(b=>b.disabled=true);const e=$('.error',form);if(e)e.remove();
  try{await work(new FormData(form));}catch(error){formError(form).textContent=message(error);}finally{buttons.forEach(b=>b.disabled=false);updateReviewControls();}
}
function specHtml(spec={}){return `<dl class="specs"><div><dt>${esc(t.size)}</dt><dd>${esc(spec.widthMm)} × ${esc(spec.heightMm)} mm</dd></div><div><dt>${esc(t.material)}</dt><dd>${esc(spec.material)}</dd></div><div><dt>${esc(t.quantity)}</dt><dd>${esc(spec.quantity)} ${esc(t.pieces)}</dd></div></dl>${spec.note?`<p class="spec-note">${esc(spec.note)}</p>`:''}`;}
function commentsHtml(comments){return comments.length?`<ol class="comment-list">${comments.map((c,i)=>`<li id="comment-${esc(c.id)}"><div class="comment-meta">${Number.isFinite(c.x)&&Number.isFinite(c.y)?`<span>${i+1}.</span>`:''}<strong>${esc(c.name)}</strong><time>${esc(fmt(c.createdAt))}</time></div><p>${esc(c.text)}</p></li>`).join('')}</ol>`:`<p class="help">${esc(t.noComments)}</p>`;}
function decisionHtml(d){if(!d)return `<p class="help">${esc(t.noDecision)}</p>`;return `<section class="decision-record ${esc(d.decision)}"><h2>${esc(d.decision==='approved'?t.approvedTitle:t.changesTitle)}</h2><p>${esc(t.decidedBy)}: <strong>${esc(d.name)}</strong></p><p class="help">${esc(t.decidedAt)}: ${esc(fmt(d.createdAt))}</p>${d.note?`<p>${esc(d.note)}</p>`:''}</section>`;}
function preview(v){return `<div class="preview"><div class="preview-bar"><span>${esc(t.version)} ${esc(v.number)}</span>${status(v.status)}</div><div class="proof-canvas" id="canvas"><p class="review-loading">${esc(t.imageLoading)}</p></div><div class="preview-foot">${esc(v.filename)} · ${new Intl.NumberFormat(lang,{maximumFractionDigits:1}).format(v.bytes/1024)} KiB</div></div>`;}
async function image(path,v,comments,review=false){
  const ticket=sequence;imageReady=false;updateReviewControls();
  try{const res=await api(path,{review});const blob=await res.blob();if(ticket!==sequence)return;
    const url=URL.createObjectURL(blob);urls.push(url);const img=new Image();img.alt=`${t.version} ${v.number}: ${reviewData?.job?.title||jobData?.job?.title||v.filename}`;
    img.onload=()=>{if(ticket!==sequence)return;const canvas=$('#canvas');if(!canvas)return;canvas.replaceChildren(img);imageReady=true;drawPins(comments);if(review)canvas.addEventListener('click',markPoint);updateReviewControls();};
    img.onerror=()=>{if(ticket!==sequence)return;imageReady=false;$('#canvas').innerHTML=`<p class="review-loading">${esc(t.imageFailed)}</p>`;updateReviewControls();};img.src=url;
  }catch(e){if(ticket!==sequence)return;if(review&&(e.status===404||e.status===409))return reviewError(e);$('#canvas').innerHTML=`<p class="review-loading">${esc(t.imageFailed)}</p>`;}
}
function drawPins(comments=[]){const canvas=$('#canvas');if(!canvas||!imageReady)return;$$('.pin',canvas).forEach(p=>p.remove());comments.forEach((c,i)=>{if(!Number.isFinite(c.x)||!Number.isFinite(c.y))return;const p=document.createElement('button');p.type='button';p.className='pin';p.textContent=String(i+1);p.style.left=Math.min(1,Math.max(0,c.x))*100+'%';p.style.top=Math.min(1,Math.max(0,c.y))*100+'%';p.setAttribute('aria-label',`${t.comment} ${i+1}: ${c.text}`);p.addEventListener('click',e=>{e.stopPropagation();document.getElementById('comment-'+c.id)?.scrollIntoView({block:'center',behavior:'smooth'});});canvas.append(p);});if(point){const p=document.createElement('span');p.className='pin selected';p.textContent='+';p.style.left=point.x*100+'%';p.style.top=point.y*100+'%';canvas.append(p);}}
function renderAuth(){header();replace(`<section class="auth"><div class="auth-story"><p class="eyebrow">ARLing Proof</p><h1>${esc(t.authTitle).replace('\n','<br>')}</h1><p class="lead">${esc(t.authIntro)}</p><ol class="auth-lines">${t.authSteps.map((s,i)=>`<li><span>0${i+1}</span>${esc(s)}</li>`).join('')}</ol></div><section class="auth-form"><div class="tabs"><button type="button" data-mode="login" aria-pressed="${authMode==='login'}">${esc(t.login)}</button><button type="button" data-mode="register" aria-pressed="${authMode==='register'}">${esc(publicRegistration?(lang==='sk'?'Vytvoriť účet':'Create an account'):t.register)}</button></div><h2>${esc(authMode==='login'?t.loginTitle:t.registerTitle)}</h2><p class="help">${esc(authMode==='login'?t.loginIntro:publicRegistration?(lang==='sk'?'Bezplatný pilot bez karty. Vytvorte si vlastný oddelený pracovný priestor.':'Free pilot, no card needed. Create your own separate workspace.'):t.registerIntro)}</p><form id="auth-form">${authMode==='register'?field(t.nameOrg,'name',{max:100,autocomplete:'organization'}):''}${field(t.email,'email',{type:'email',max:254,autocomplete:'username'})}${field(t.password,'password',{type:'password',max:256,autocomplete:authMode==='login'?'current-password':'new-password',help:authMode==='register'?t.passwordHelp:''})}${authMode==='register'&&!publicRegistration?field(t.pilotCode,'pilotCode',{max:256}):''}<button class="btn primary" type="submit">${esc(authMode==='login'?t.login:t.createAccount)}</button></form><p class="help">${esc(t.pilot)}</p><a class="text-button" href="https://arling.sk/proof/${lang==='sk'?'sk/':''}#pilot">${esc(lang==='sk'?'Rozsah, súkromie a pomoc':'Scope, privacy and help')}</a></section></section>`);
  $$('[data-mode]').forEach(b=>b.onclick=()=>{authMode=b.dataset.mode;renderAuth();});
  $('#auth-form').onsubmit=e=>{e.preventDefault();submit(e.currentTarget,async fd=>{if(new TextEncoder().encode(fd.get('password')).length>256)throw new Error(t.passwordHelp);auth=await json('auth/'+authMode,{method:'POST',body:Object.fromEntries(fd)});header();await route();});};
}
async function showJobs(){const ticket=++sequence;loading();const data=await json('jobs');if(ticket!==sequence)return;jobs=data.jobs;jobData=null;header();replace(`<section class="workspace"><div class="workspace-heading"><div><p class="eyebrow">${esc(auth.workspace.name)}</p><h1>${esc(t.jobs)}</h1></div><div class="actions">${button(t.newJob,'new-job','primary')}</div></div><aside id="test-billing" class="test-billing" hidden></aside><nav class="summary" aria-label="${esc(t.jobs)}">${['all','pending','approved','changes_requested'].map(s=>`<button type="button" data-filter="${s}" aria-pressed="${filter===s}"><strong>${s==='all'?jobs.length:jobs.filter(j=>j.status===s).length}</strong><span>${esc(t[s])}</span></button>`).join('')}</nav><div class="ledger-tools"><label class="sr-only" for="search">${esc(t.search)}</label><input id="search" type="search" placeholder="${esc(t.search)}" value="${esc(query)}" maxlength="160">${button(t.refresh,'refresh')}</div><div id="jobs-list"></div><p class="pilot-note">${esc(t.pilot)}</p><details><summary>${esc(t.limits)}</summary><p class="help">${esc(t.limitHelp)}</p></details></section>`);renderRows();await renderTestBilling(ticket);
  $('#search').oninput=e=>{query=e.target.value;renderRows();};$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));renderRows();});$('[data-action=new-job]').onclick=createJob;$('[data-action=refresh]').onclick=()=>safe(showJobs);
}
function renderRows(){const list=jobs.filter(j=>(filter==='all'||j.status===filter)&&`${j.title} ${j.customer}`.toLocaleLowerCase(lang).includes(query.toLocaleLowerCase(lang)));$('#jobs-list').innerHTML=!jobs.length?`<div class="blank"><h2>${esc(t.emptyTitle)}</h2><p>${esc(t.emptyText)}</p>${button(t.newJob,'first-job','primary')}</div>`:!list.length?`<p class="blank">${esc(t.noResults)}</p>`:`<table class="ledger"><thead><tr><th>${esc(t.job)}</th><th>${esc(t.decisionTitle)}</th><th>${esc(t.updated)}</th><th>${esc(t.version)}</th></tr></thead><tbody>${list.map(j=>`<tr><td><button class="job-title" data-job="${esc(j.id)}">${esc(j.title)}</button><span class="customer">${esc(j.customer)}</span></td><td>${status(j.status)}</td><td>${esc(fmt(j.updatedAt))}</td><td>${esc(j.versionNumber||0)}</td></tr>`).join('')}</tbody></table>`;$$('[data-job]').forEach(b=>b.onclick=()=>navigate('job',b.dataset.job));const first=$('[data-action=first-job]');if(first)first.onclick=createJob;}
function createJob(){dialog(t.newJob,`<form id="new-job-form">${field(t.jobTitle,'title')}${field(t.customer,'customer')}${area(`${t.note} (${t.optional})`,'note')}<div class="actions"><button class="btn primary" type="submit">${esc(t.createJob)}</button></div></form>`);$('#new-job-form').onsubmit=e=>{e.preventDefault();submit(e.currentTarget,async fd=>{const d=await json('jobs',{method:'POST',body:Object.fromEntries(fd)});modal.close();navigate('job',d.job.id);});};}
async function renderTestBilling(ticket){
  const panel=$('#test-billing');if(!panel||new URLSearchParams(location.search).get('test')!=='1')return;
  const copy=lang==='sk'?{title:'TEST platby. Žiadne skutočné peniaze.',text:'Tento blok overuje iba skúšobnú platbu. Nevytvára živé predplatné ani živé platené oprávnenie.',loading:'Načítavam stav zo servera…',off:'Testovacia pokladňa nie je nakonfigurovaná.',pilot:'Pilot zostáva dostupný bez platby.',until:'Skúšobný prístup do',unpaid:'Skúšobná platba zatiaľ nie je potvrdená.',terms:'30 dní, jednorazovo, bez automatického obnovenia.',button:'Otvoriť TEST pokladňu',refresh:'Obnoviť stav zo servera',limited:'Testovací režim vyžaduje skúšobnú platbu na nové zákazky. Existujúce zákazky a exporty zostávajú dostupné.'}:{title:'Payment TEST. No real money.',text:'This section checks a test payment only. It does not create a live subscription or live paid access.',loading:'Loading the server status…',off:'The test checkout is not configured.',pilot:'The pilot remains available without payment.',until:'Test access until',unpaid:'No test payment has been confirmed yet.',terms:'30 days, one payment, no automatic renewal.',button:'Open TEST checkout',refresh:'Refresh server status',limited:'Test mode requires a test payment for new jobs. Existing jobs and exports remain available.'};
  panel.hidden=false;panel.innerHTML=`<h2>${esc(copy.title)}</h2><p>${esc(copy.text)}</p><p class="help">${esc(copy.loading)}</p>`;
  try{const b=await json('billing?test=1');if(ticket!==sequence)return;const checkout=b.testCheckout;let validUrl='';if(b.enabled===false&&b.testEnabled===true&&checkout?.amount===900&&checkout.currency==='eur'&&checkout.days===30&&checkout.recurring===false){try{const u=new URL(checkout.url);if(u.origin==='https://buy.stripe.com'&&/^\/test_[A-Za-z0-9]+$/.test(u.pathname)&&!u.username&&!u.password)validUrl=u.href;}catch{}}
    panel.innerHTML=`<h2>${esc(copy.title)}</h2><p>${esc(copy.text)}</p><p class="help">${esc(b.mode==='pilot'?copy.pilot:b.canCreateJobs?(lang==='sk'?'TEST: nové zákazky sú povolené.':'TEST: new jobs are allowed.'):copy.limited)}</p><p class="help">${esc(b.paidThrough?copy.until+': '+fmt(b.paidThrough):copy.unpaid)}</p>${validUrl?`<p class="help">${esc(new Intl.NumberFormat(lang,{style:'currency',currency:'EUR'}).format(checkout.amount/100))} · TEST · ${esc(copy.terms)}</p><div class="actions"><a class="btn" id="test-checkout" href="${esc(validUrl)}" rel="noreferrer noopener">${esc(copy.button)}</a><button type="button" class="text-button" data-action="billing-refresh">${esc(copy.refresh)}</button></div>`:`<p class="help">${esc(copy.off)}</p>`}`;
    const refresh=$('[data-action=billing-refresh]');if(refresh)refresh.onclick=()=>renderTestBilling(sequence);
    if(b.mode==='test'&&b.canCreateJobs===false)$$('[data-action=new-job],[data-action=first-job]').forEach(button=>button.disabled=true);
  }catch(e){if(ticket===sequence)panel.innerHTML=`<h2>${esc(copy.title)}</h2><p>${esc(copy.text)}</p><p class="help">${esc(message(e))}</p>`;}
}
async function showJob(id){const ticket=++sequence;loading();const data=await json('jobs/'+encodeURIComponent(id));if(ticket!==sequence)return;jobData=data;const v=data.versions.find(v=>v.id===chosenVersion)||data.versions.find(v=>v.id===data.job.currentVersionId)||data.versions.at(-1);chosenVersion=v?.id||'';const comments=data.comments.filter(c=>c.versionId===v?.id),decision=data.decisions.find(d=>d.versionId===v?.id);header();replace(`<section class="workspace"><button class="text-button back" data-action="back">← ${esc(t.back)}</button><div class="job-heading"><div><p class="eyebrow">${esc(t.job)}</p><h1>${esc(data.job.title)}</h1><p class="customer">${esc(data.job.customer)}</p></div><div class="actions">${v?button(t.record,'record'):''}${button(v?t.newVersion:t.firstVersion,'upload','primary')}</div></div>${data.job.note?`<p class="spec-note">${esc(data.job.note)}</p><hr class="rule">`:''}<div class="job-layout"><section>${v?preview(v):`<div class="blank"><h2>${esc(t.noVersion)}</h2><p>${esc(t.uploadHelp)}</p></div>`}${v?`<div class="actions side-block">${button(t.download,'download')}<span class="help">${esc(fmt(v.createdAt))}</span></div><section class="side-block"><h2>${esc(t.comments)}</h2>${commentsHtml(comments)}</section>${decisionHtml(decision)}`:''}</section><aside>${v?`<div class="spec-title"><h2>${esc(t.specification)}</h2><span class="help">${esc(t.version)} ${esc(v.number)}${v.id===data.job.currentVersionId?' · '+esc(t.current):''}</span></div>${specHtml(v.spec)}<section class="side-block"><h2>${esc(t.share)}</h2><p class="help">${esc(t.shareHelp)}</p><div class="actions side-block">${button(data.links.some(l=>!l.revokedAt&&new Date(l.expiresAt)>new Date())?t.shareReplace:t.shareNew,'share','primary')}</div><div id="new-link"></div>${data.links.map(l=>`<div class="link-item"><span>${esc(l.revokedAt?t.revoked:t.expires)}<br>${esc(fmt(l.revokedAt||l.expiresAt))}</span>${!l.revokedAt&&new Date(l.expiresAt)>new Date()?`<button type="button" class="text-button" data-revoke="${esc(l.id)}">${esc(t.revoke)}</button>`:''}</div>`).join('')}</section><section class="side-block"><h2>${esc(t.history)}</h2><ol class="version-list">${[...data.versions].sort((a,b)=>b.number-a.number).map(ver=>`<li><button type="button" data-version="${esc(ver.id)}" aria-pressed="${ver.id===v.id}"><span><strong>${esc(t.version)} ${esc(ver.number)}</strong><time>${esc(fmt(ver.createdAt))}</time></span>${status(ver.status)}</button></li>`).join('')}</ol></section>`:''}</aside></div></section>`);
  $('[data-action=back]').onclick=()=>navigate();$('[data-action=upload]').onclick=()=>uploadVersion(data.job.id);if(!v)return;
  image(`jobs/${encodeURIComponent(id)}/versions/${encodeURIComponent(v.id)}/file`,v,comments);
  $('[data-action=record]').onclick=()=>navigate('record',id);$('[data-action=download]').onclick=()=>safe(async()=>saveBlob(await(await api(`jobs/${encodeURIComponent(id)}/versions/${encodeURIComponent(v.id)}/file`)).blob(),v.filename));
  $$('[data-version]').forEach(b=>b.onclick=()=>{chosenVersion=b.dataset.version;safe(()=>showJob(id));});
  $('[data-action=share]').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{activeLink={...(await json(`jobs/${encodeURIComponent(id)}/links`,{method:'POST',body:{}})),jobId:id};await showJob(id);renderNewLink();}catch(err){notify(message(err));}finally{b.disabled=false;}};
  $$('[data-revoke]').forEach(b=>b.onclick=()=>safe(async()=>{await json(`jobs/${encodeURIComponent(id)}/links/${encodeURIComponent(b.dataset.revoke)}/revoke`,{method:'POST',body:{}});activeLink=null;await showJob(id);notify(t.revokedNotice);}));
  if(activeLink?.jobId===id&&data.links.some(l=>l.id===activeLink.id&&!l.revokedAt))renderNewLink();
}
function renderNewLink(){if(!activeLink||!$('#new-link'))return;const url=new URL(base);url.hash=new URLSearchParams({review:activeLink.token,lang}).toString();$('#new-link').innerHTML=`<div class="link-box"><label for="share-link">${esc(t.share)}</label><input id="share-link" type="text" readonly value="${esc(url.href)}"><p class="help">${esc(t.expires)}: ${esc(fmt(activeLink.expiresAt))}</p><div class="actions">${button(t.copy,'copy')}</div></div>`;$('[data-action=copy]').onclick=async()=>{try{await navigator.clipboard.writeText(url.href);notify(t.copied);}catch{$('#share-link').focus();$('#share-link').select();notify(t.copyFallback);}};}
function uploadVersion(id){const current=jobData.versions.find(v=>v.id===jobData.job.currentVersionId);dialog(current?t.newVersion:t.firstVersion,`<form id="upload-form"><p class="help">${esc(t.uploadWarning)}</p><hr class="rule"><div class="field"><label for="upload-file">${esc(t.file)}</label><input id="upload-file" name="file" type="file" accept="image/png,image/jpeg,.png,.jpg,.jpeg" required><p class="help">${esc(t.uploadHelp)}</p></div>${field(t.material,'material',{value:current?.spec.material||''})}<div class="field-row three">${field(t.width,'widthMm',{type:'number',value:current?.spec.widthMm||'',min:'0.001',max:100000,step:'any'})}${field(t.height,'heightMm',{type:'number',value:current?.spec.heightMm||'',min:'0.001',max:100000,step:'any'})}${field(t.quantity,'quantity',{type:'number',value:current?.spec.quantity||1,min:1,max:1000000})}</div>${area(`${t.note} (${t.optional})`,'note',current?.spec.note||'')}<button class="btn primary wide" type="submit">${esc(t.upload)}</button></form>`);$('#upload-form').onsubmit=e=>{e.preventDefault();submit(e.currentTarget,async fd=>{const f=fd.get('file');if(!f?.size||f.size>5*1024*1024||!['image/png','image/jpeg'].includes(f.type))throw new Error(t.fileSize);const spec={material:fd.get('material').trim(),widthMm:Number(fd.get('widthMm')),heightMm:Number(fd.get('heightMm')),quantity:Number(fd.get('quantity')),note:fd.get('note').trim()};await json(`jobs/${encodeURIComponent(id)}/versions`,{method:'POST',raw:true,body:f,headers:{'Content-Type':f.type,'X-File-Name':encodeURIComponent(f.name),'X-Proof-Spec':encodeURIComponent(JSON.stringify(spec))}});chosenVersion='';modal.close();await showJob(id);});};}
function navigate(key='',value=''){chosenVersion='';const hash=key?new URLSearchParams({[key]:value}).toString():'';if(location.hash.slice(1)===hash)safe(route);else location.hash=hash;}
function updateReviewControls(){if(!token)return;$$('[data-mutate]').forEach(b=>b.disabled=!imageReady||conflict||!!reviewData?.decision);const hint=$('#load-hint');if(hint)hint.hidden=imageReady&&!conflict;}
function reviewError(e){if(e.status===404){++sequence;reviewData=null;replace(`<section class="review"><p class="eyebrow">ARLing Proof</p><h1>${esc(t.unavailableTitle)}</h1><p class="review-intro">${esc(t.unavailable)}</p></section>`);return;}if(['version_conflict','already_decided'].includes(e.code)){conflict=true;annotating=false;$('#canvas')?.classList.remove('annotating');updateReviewControls();let alert=$('#review-conflict');if(!alert){alert=document.createElement('div');alert.id='review-conflict';alert.className='error';alert.setAttribute('role','alert');main.prepend(alert);}alert.innerHTML=`<p>${esc(t.stale)}</p><button type="button" class="text-button">${esc(t.reload)}</button>`;$('button',alert).onclick=()=>safe(showReview);return;}notify(message(e));}
async function showReview(){const ticket=++sequence;loading();header();let data;try{data=await json('review',{review:true});}catch(e){if(ticket===sequence){main.removeAttribute('aria-busy');reviewError(e);}return;}if(ticket!==sequence)return;reviewData=data;conflict=false;point=null;annotating=false;const v=data.version;replace(`<section class="review"><div class="job-heading"><div><p class="eyebrow">${esc(t.reviewEyebrow)}</p><h1>${esc(data.job.title)}</h1><p class="customer">${esc(data.job.customer)}</p><p class="review-intro">${esc(t.reviewIntro)}</p></div><div class="actions">${button(t.refresh,'refresh-review')}</div></div><div class="job-layout"><section>${preview(v)}${!data.decision?`<div class="review-tools">${button(t.annotate,'annotate')}<p id="point-hint" class="help" role="status"></p></div>`:''}<p class="help">${esc(t.reviewLimit)}</p><section class="side-block"><h2>${esc(t.comments)}</h2>${commentsHtml(data.comments)}</section></section><aside><div class="spec-title"><h2>${esc(t.specification)}</h2><span class="help">${esc(t.version)} ${esc(v.number)}</span></div>${specHtml(v.spec)}${data.decision?`${decisionHtml(data.decision)}<p class="help">${esc(t.finalDecision)}</p>`:`<section class="review-form"><h2>${esc(t.decisionTitle)}</h2><div class="field"><label for="review-name">${esc(t.reviewName)}</label><input id="review-name" name="name" value="${esc(reviewerName)}" autocomplete="name" maxlength="100" required></div><details id="comment-details"><summary>${esc(t.comment)}</summary><form id="comment-form">${area(t.commentText,'comment','',3000,true)}<p class="comment-coordinate" id="coordinate" hidden></p><button type="button" class="text-button" data-action="clear-point" hidden>${esc(t.clearPoint)}</button><button class="btn wide" type="submit" data-mutate disabled>${esc(t.commentSend)}</button></form></details><div class="review-tabs"><button type="button" data-decision="approved" aria-pressed="${decisionMode==='approved'}">${esc(t.approve)}</button><button type="button" data-decision="changes_requested" aria-pressed="${decisionMode==='changes_requested'}">${esc(t.changes)}</button></div><form id="decision-form"><div id="decision-fields"></div><p id="load-hint" class="help">${esc(t.disabledControls)}</p></form></section>`}</aside></div></section>`);
  $('[data-action=refresh-review]').onclick=()=>safe(showReview);
  if(!data.decision){$('#review-name').oninput=e=>{reviewerName=e.target.value;e.target.setCustomValidity('');};$('[data-action=annotate]').onclick=()=>{if(!imageReady||conflict)return;annotating=!annotating;$('#canvas').classList.toggle('annotating',annotating);$('#point-hint').textContent=annotating?t.annotating:'';};$('[data-action=clear-point]').onclick=()=>{point=null;setPointUi();};$('#comment-form').onsubmit=e=>{e.preventDefault();if(!readyName()||!imageReady||conflict)return;submit(e.currentTarget,async fd=>{try{await json('review/comments',{method:'POST',review:true,body:{versionId:v.id,name:reviewerName.trim(),text:fd.get('comment').trim(),x:point?.x??null,y:point?.y??null}});await showReview();notify(t.savedComment);}catch(err){reviewError(err);throw err;}});};$$('[data-decision]').forEach(b=>b.onclick=()=>{decisionMode=b.dataset.decision;renderDecisionFields();});renderDecisionFields();$('#decision-form').onsubmit=e=>{e.preventDefault();if(!readyName()||!imageReady||conflict)return;submit(e.currentTarget,async fd=>{try{await json('review/decision',{method:'POST',review:true,body:{versionId:v.id,name:reviewerName.trim(),decision:decisionMode,note:String(fd.get('decisionNote')||'').trim(),confirmed:decisionMode==='approved'?fd.get('confirmed')==='on':false}});await showReview();notify(t.decisionSaved);}catch(err){reviewError(err);throw err;}});};}
  await image('review/file?versionId='+encodeURIComponent(v.id),v,data.comments,true);
}
function readyName(){const n=$('#review-name');if(!n?.value.trim()){n?.setCustomValidity(t.invalidForm);n?.reportValidity();n?.focus();return false;}reviewerName=n.value;return true;}
function renderDecisionFields(){const old=$('#f-decisionNote')?.value||'';$('#decision-fields').innerHTML=area(`${t.decisionNote}${decisionMode==='approved'?' ('+t.optional+')':''}`,'decisionNote',old,2000,decisionMode==='changes_requested')+(decisionMode==='approved'?`<label class="check-label"><input type="checkbox" name="confirmed" required><span>${esc(t.approvalCheck)}</span></label><p class="help">${esc(t.approveHelp)}</p>`:`<p class="help">${esc(t.changesHelp)}</p>`)+`<button class="btn primary wide" type="submit" data-mutate disabled>${esc(decisionMode==='approved'?t.approve:t.changes)}</button>`;$$('[data-decision]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.decision===decisionMode));updateReviewControls();}
function markPoint(e){if(!annotating||!imageReady||conflict)return;const img=$('img',$('#canvas')),rect=img.getBoundingClientRect();point={x:Math.min(1,Math.max(0,(e.clientX-rect.left)/rect.width)),y:Math.min(1,Math.max(0,(e.clientY-rect.top)/rect.height))};annotating=false;$('#canvas').classList.remove('annotating');setPointUi();$('#comment-details').open=true;$('#f-comment').focus();}
function setPointUi(){drawPins(reviewData?.comments||[]);$('#point-hint').textContent=point?t.point:'';$('#coordinate').hidden=!point;$('#coordinate').textContent=point?t.point:'';$('[data-action=clear-point]').hidden=!point;}
function saveBlob(blob,filename){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=String(filename||'proof-export.json').replace(/[\\/\x00-\x1f]/g,'_');document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function showRecord(id){const ticket=++sequence;loading();const data=await json(`jobs/${encodeURIComponent(id)}/export`);if(ticket!==sequence)return;header();replace(`<article class="record"><div class="actions no-print"><button class="text-button back" data-action="back-job">← ${esc(t.job)}</button><span class="push"></span>${button(t.export,'export')}${button(t.print,'print','primary')}</div><header class="record-head"><p class="eyebrow">ARLing Proof</p><h1>${esc(t.recordTitle)}</h1><h2>${esc(data.job.title)}</h2><p class="customer">${esc(data.job.customer)}</p><p class="help">${esc(data.workspace.name)} · ${esc(t.exported)}: ${esc(fmt(data.exportedAt))}</p><p class="help">${esc(t.recordVersion)}</p><p class="help">${esc(t.current)}: ${esc(t.version)} ${esc(data.job.versionNumber)} · ${esc(t[data.job.status]||data.job.status)}</p>${data.job.status!=='approved'?`<p class="record-error">${esc(t.notApproved)}</p>`:''}</header>${[...data.versions].sort((a,b)=>b.number-a.number).map(v=>`<section class="record-version"><h2>${esc(t.version)} ${esc(v.number)}${v.id===data.job.currentVersionId?' · '+esc(t.current):''}</h2>${specHtml(v.spec)}<p class="help">${esc(v.filename)} · ${esc(fmt(v.createdAt))}</p><p class="mono">${esc(t.hash)}<br>${esc(v.sha256)}</p>${decisionHtml(data.decisions.find(d=>d.versionId===v.id))}<h3 class="side-block">${esc(t.comments)}</h3>${commentsHtml(data.comments.filter(c=>c.versionId===v.id))}</section>`).join('')}<p class="help">${esc(t.recordHelp)}</p></article>`);$('[data-action=back-job]').onclick=()=>navigate('job',id);$('[data-action=export]').onclick=()=>saveBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'proof-'+id+'.json');$('[data-action=print]').onclick=()=>window.print();}
async function safe(fn){try{await fn();}catch(e){main.removeAttribute('aria-busy');if(e.status===401&&!token){auth=null;renderAuth();}notify(message(e));}}
async function route(){token=parts().get('review')||'';header();if(token)return showReview();if(!auth)return renderAuth();if(parts().get('record'))return showRecord(parts().get('record'));if(parts().get('job'))return showJob(parts().get('job'));return showJobs();}
$('#modal-close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
$('#language').onchange=()=>{$('#notice').hidden=true;lang=$('#language').value;try{localStorage.setItem('proof-language',lang);}catch{}modal.close();safe(route);};
$('#logout').onclick=()=>safe(async()=>{await json('auth/logout',{method:'POST',body:{}});auth=null;activeLink=null;location.hash='';renderAuth();});
window.addEventListener('hashchange',()=>{const explicit=parts().get('lang');if(TEXTY[explicit])lang=explicit;point=null;reviewerName='';conflict=false;chosenVersion='';safe(route);});
window.addEventListener('pageshow',e=>{if(e.persisted)safe(route);});
try{publicRegistration=(await json('access')).publicRegistration===true;}catch{}
header();if(token)await safe(route);else{try{auth=await json('auth/me');}catch(e){if(e.status!==401)notify(message(e));}await safe(route);}
