// Cena sa doplna z tej istej konstanty ako existujuce tlacidlo platby.
export const TEXTY_DAVKY = {
  en: {
    title: 'More invoices? Create a batch from CSV', intro: 'Enter the seller and choose the profile in the form below. Your CSV supplies the buyers, dates and line items. Repeated invoice numbers group lines into one invoice.',
    scope: 'Up to 100 invoices and 500 lines per batch. UBL XML in a ZIP; Peppol delivery is not included. Supported checks run before payment, but do not guarantee receiver acceptance.',
    privacy: 'The CSV stays in this tab and is kept here for your return from payment. Clear it with the button below. No invoice data is uploaded.',
    sample: 'Download CSV template', load: 'Load fictional example', file: 'Choose CSV file', paste: 'Or paste CSV', check: 'Check batch', clear: 'Clear batch', seller: 'Edit seller and profile',
    format: 'CSV: UTF-8; comma or semicolon. Dates: YYYY-MM-DD. Numbers: decimal dot or comma, without thousands separators. Keep identifiers as text to preserve leading zeros. Enter VAT categories and rates yourself; this tool does not choose the tax treatment.',
    columns: 'Required column names', optional: 'Optional column names', fresh: 'Check the batch after changing the CSV, seller or profile.', busy: 'Checking…',
    checked: '{n} invoices checked. Review the totals and documents below before buying.', ready: 'All invoices passed our supported checks.', blocked: 'Correct the listed errors before buying or downloading. No invoice is silently skipped.',
    row: 'CSV row', invoice: 'Invoice', lines: 'Rows', total: 'Amount due', preview: 'Preview document', errors: 'Errors', warnings: 'Warnings',
    buy: 'Unlock XML downloads for 30 days, {price} excl. VAT', download: 'Download batch ZIP', unlocked: 'Your existing 30-day access includes batch XML downloads.',
    price: 'Batch checking and preview are free. ZIP download uses the existing 30-day access for {price} excl. VAT, a one-time payment with no subscription. The one-invoice purchase does not unlock batches.',
    return: 'After payment, this batch reopens on the invoice page in the same language and tab.', storage: 'This browser cannot keep the batch for your return. Save the CSV yourself before payment, then import it again.',
    failure: 'The batch could not be processed. Check the CSV and try again.', example: 'Fictional example loaded. Enter your own seller below; replace the example buyers before issuing invoices.',
    problems: { size: 'Maximum CSV size: 1 MB.', empty: 'Add a header and at least one data row.', rows: 'Maximum 500 data rows.', quotes: 'Check CSV quotes and separators.', header_duplicate: 'A column name appears twice.', header_unknown: 'Unknown column. Use the template names.', header_missing: 'A required column is missing.', columns: 'The row has a different number of columns.', characters: 'Unsupported control character.', required: 'Fill in this required field.', length: 'Invoice number is too long (maximum 80 characters).', currency: 'Use an uppercase three-letter currency code.', country: 'Use an uppercase two-letter country code.', date: 'Use a real date in YYYY-MM-DD format.', due_date: 'Due date precedes issue date.', category: 'Supported VAT categories: S, Z, E, AE, O.', number: 'Invalid number, range or precision. Do not use thousands separators.', rate_category: 'S requires a positive VAT rate; other supported categories require zero.', amount: 'A line exceeds the supported amount.', duplicate: 'Identical row repeated. Remove the duplicate or combine the quantities.', conflict: 'The same invoice number has conflicting buyer or invoice details.', invoices: 'Maximum 100 invoices.', iban: 'Enter a valid seller IBAN for SEPA payment.' }
  },
  de: {
    title: 'Mehrere Rechnungen? Einen Stapel aus CSV erstellen', intro: 'Tragen Sie den Verkäufer ein und wählen Sie das Profil im Formular unten. Käufer, Daten und Positionen kommen aus der CSV. Gleiche Rechnungsnummern fassen Positionen zu einer Rechnung zusammen.',
    scope: 'Bis zu 100 Rechnungen und 500 Positionen pro Stapel. UBL-XML in einer ZIP-Datei; Peppol-Versand ist nicht enthalten. Unsere unterstützten Prüfungen laufen vor der Zahlung, garantieren aber keine Annahme durch den Empfänger.',
    privacy: 'Die CSV bleibt in diesem Tab und wird für die Rückkehr von der Zahlung hier aufbewahrt. Mit der Schaltfläche unten können Sie sie leeren. Keine Rechnungsdaten werden hochgeladen.',
    sample: 'CSV-Vorlage herunterladen', load: 'Fiktives Beispiel laden', file: 'CSV-Datei wählen', paste: 'Oder CSV einfügen', check: 'Stapel prüfen', clear: 'Stapel leeren', seller: 'Verkäufer und Profil bearbeiten',
    format: 'CSV: UTF-8; Komma oder Semikolon. Datum: JJJJ-MM-TT. Zahlen: Dezimalpunkt oder Komma, ohne Tausendertrennzeichen. Kennungen als Text behandeln, damit führende Nullen erhalten bleiben. Steuerkategorien und Steuersätze tragen Sie selbst ein; das Werkzeug entscheidet nicht über die Besteuerung.',
    columns: 'Pflichtspalten', optional: 'Optionale Spalten', fresh: 'Nach Änderungen an CSV, Verkäufer oder Profil den Stapel erneut prüfen.', busy: 'Prüfung läuft…',
    checked: '{n} Rechnungen geprüft. Kontrollieren Sie Summen und Belege unten vor dem Kauf.', ready: 'Alle Rechnungen haben unsere unterstützten Prüfungen bestanden.', blocked: 'Beheben Sie die angezeigten Fehler vor Kauf oder Download. Keine Rechnung wird stillschweigend übersprungen.',
    row: 'CSV-Zeile', invoice: 'Rechnung', lines: 'Zeilen', total: 'Zahlbetrag', preview: 'Beleg ansehen', errors: 'Fehler', warnings: 'Warnungen',
    buy: 'XML-Downloads für 30 Tage freischalten, {price} zzgl. MwSt.', download: 'Stapel als ZIP herunterladen', unlocked: 'Ihr bestehender 30-Tage-Zugang umfasst XML-Stapel.',
    price: 'Prüfung und Vorschau sind kostenlos. Der ZIP-Download nutzt den bestehenden 30-Tage-Zugang für {price} zzgl. MwSt., eine einmalige Zahlung ohne Abo. Der Kauf einer einzelnen Rechnung schaltet keine Stapel frei.',
    return: 'Nach der Zahlung öffnet sich dieser Stapel auf der Rechnungsseite in derselben Sprache und demselben Tab.', storage: 'Dieser Browser kann den Stapel nicht für die Rückkehr speichern. Speichern Sie die CSV vor der Zahlung selbst und importieren Sie sie danach erneut.',
    failure: 'Der Stapel konnte nicht verarbeitet werden. Prüfen Sie die CSV und versuchen Sie es erneut.', example: 'Fiktives Beispiel geladen. Tragen Sie unten Ihren Verkäufer ein; ersetzen Sie die Beispielkäufer, bevor Sie Rechnungen ausstellen.',
    problems: { size: 'Maximale CSV-Größe: 1 MB.', empty: 'Kopfzeile und mindestens eine Datenzeile erforderlich.', rows: 'Höchstens 500 Datenzeilen.', quotes: 'Anführungszeichen und Trennzeichen prüfen.', header_duplicate: 'Ein Spaltenname ist doppelt.', header_unknown: 'Unbekannte Spalte. Namen der Vorlage verwenden.', header_missing: 'Eine Pflichtspalte fehlt.', columns: 'Die Anzahl der Spalten weicht ab.', characters: 'Nicht unterstütztes Steuerzeichen.', required: 'Pflichtfeld ausfüllen.', length: 'Rechnungsnummer zu lang (höchstens 80 Zeichen).', currency: 'Dreistelligen Währungscode in Großbuchstaben verwenden.', country: 'Zweistelligen Ländercode in Großbuchstaben verwenden.', date: 'Gültiges Datum im Format JJJJ-MM-TT verwenden.', due_date: 'Fälligkeit liegt vor dem Rechnungsdatum.', category: 'Unterstützte Steuerkategorien: S, Z, E, AE, O.', number: 'Ungültige Zahl, Größe oder Genauigkeit. Keine Tausendertrennzeichen verwenden.', rate_category: 'S verlangt einen positiven Steuersatz; andere unterstützte Kategorien verlangen null.', amount: 'Der Positionsbetrag überschreitet das Limit.', duplicate: 'Identische Zeile doppelt. Duplikat entfernen oder Mengen zusammenfassen.', conflict: 'Gleiche Rechnungsnummer mit abweichenden Käufer- oder Rechnungsdaten.', invoices: 'Höchstens 100 Rechnungen.', iban: 'Für SEPA-Zahlung eine gültige Verkäufer-IBAN eintragen.' }
  },
  sk: {
    title: 'Viac faktúr? Vytvorte dávku z CSV', intro: 'Doplňte dodávateľa a zvoľte profil vo formulári nižšie. Odberatelia, dátumy a položky prídu z CSV. Riadky s rovnakým číslom faktúry sa spoja do jednej faktúry.',
    scope: 'Najviac 100 faktúr a 500 položiek v dávke. UBL XML v ZIP súbore; odosielanie cez Peppol nie je súčasťou. Podporované kontroly bežia pred platbou, ale nezaručujú prijatie príjemcom.',
    privacy: 'CSV zostáva v tejto karte a uchová sa tu na návrat z platby. Vyprázdnite ho tlačidlom nižšie. Žiadne fakturačné údaje sa neodosielajú.',
    sample: 'Stiahnuť CSV vzor', load: 'Načítať vymyslený príklad', file: 'Vybrať CSV súbor', paste: 'Alebo vložte CSV', check: 'Skontrolovať dávku', clear: 'Vyprázdniť dávku', seller: 'Upraviť dodávateľa a profil',
    format: 'CSV: UTF-8; čiarka alebo bodkočiarka. Dátumy: RRRR-MM-DD. Čísla: desatinná bodka alebo čiarka, bez oddeľovača tisícov. Identifikátory uchovajte ako text, aby zostali úvodné nuly. Kategórie a sadzby DPH zadávate sami; nástroj nerozhoduje o zdanení.',
    columns: 'Povinné názvy stĺpcov', optional: 'Voliteľné názvy stĺpcov', fresh: 'Po zmene CSV, dodávateľa alebo profilu dávku znova skontrolujte.', busy: 'Kontrolujem…',
    checked: 'Skontrolované faktúry: {n}. Pred nákupom si pozrite sumy a doklady nižšie.', ready: 'Všetky faktúry prešli podporovanými kontrolami.', blocked: 'Pred nákupom alebo stiahnutím opravte uvedené chyby. Žiadna faktúra sa potichu nevynechá.',
    row: 'Riadok CSV', invoice: 'Faktúra', lines: 'Riadky', total: 'Na úhradu', preview: 'Zobraziť doklad', errors: 'Chyby', warnings: 'Upozornenia',
    buy: 'Odomknúť XML na 30 dní za {price} bez DPH', download: 'Stiahnuť dávku ZIP', unlocked: 'Váš existujúci prístup na 30 dní zahŕňa dávkové sťahovanie XML.',
    price: 'Kontrola a náhľad dávky sú zadarmo. ZIP používa existujúci prístup na 30 dní za {price} bez DPH, jednorazovo bez predplatného. Nákup jednej faktúry dávky neodomyká.',
    return: 'Po platbe sa táto dávka otvorí na stránke faktúr v rovnakom jazyku a karte.', storage: 'Tento prehliadač nevie uchovať dávku na návrat. Pred platbou si CSV uložte a potom ho znova načítajte.',
    failure: 'Dávku sa nepodarilo spracovať. Skontrolujte CSV a skúste znova.', example: 'Načítaný vymyslený príklad. Nižšie doplňte vlastného dodávateľa a pred vystavením nahraďte vzorových odberateľov.',
    problems: { size: 'Najväčšia veľkosť CSV: 1 MB.', empty: 'Pridajte hlavičku a aspoň jeden dátový riadok.', rows: 'Najviac 500 dátových riadkov.', quotes: 'Skontrolujte úvodzovky a oddeľovače CSV.', header_duplicate: 'Názov stĺpca sa opakuje.', header_unknown: 'Neznámy stĺpec. Použite názvy zo vzoru.', header_missing: 'Chýba povinný stĺpec.', columns: 'Riadok má iný počet stĺpcov.', characters: 'Nepodporovaný riadiaci znak.', required: 'Vyplňte povinné pole.', length: 'Číslo faktúry je príliš dlhé (najviac 80 znakov).', currency: 'Použite trojpísmenový kód meny veľkými písmenami.', country: 'Použite dvojpísmenový kód krajiny veľkými písmenami.', date: 'Použite existujúci dátum vo formáte RRRR-MM-DD.', due_date: 'Splatnosť je pred vystavením.', category: 'Podporované kategórie DPH: S, Z, E, AE, O.', number: 'Neplatné číslo, rozsah alebo presnosť. Nepoužívajte oddeľovače tisícov.', rate_category: 'S vyžaduje kladnú sadzbu DPH; ostatné podporované kategórie vyžadujú nulu.', amount: 'Suma položky presahuje podporovaný rozsah.', duplicate: 'Zhodný riadok sa opakuje. Odstráňte duplicitu alebo spojte množstvá.', conflict: 'Rovnaké číslo faktúry má odlišné údaje odberateľa alebo faktúry.', invoices: 'Najviac 100 faktúr.', iban: 'Pre SEPA platbu zadajte platný IBAN dodávateľa.' }
  },
  cs: {
    title: 'Více faktur? Vytvořte dávku z CSV', intro: 'Doplňte dodavatele a zvolte profil ve formuláři níže. Odběratelé, data a položky přijdou z CSV. Řádky se stejným číslem faktury se spojí do jedné faktury.',
    scope: 'Nejvýše 100 faktur a 500 položek v dávce. UBL XML v ZIP souboru; odesílání přes Peppol není součástí. Podporované kontroly běží před platbou, ale nezaručují přijetí příjemcem.',
    privacy: 'CSV zůstává v této kartě a uchová se zde pro návrat z platby. Vyprázdněte jej tlačítkem níže. Žádné fakturační údaje se neodesílají.',
    sample: 'Stáhnout CSV vzor', load: 'Načíst smyšlený příklad', file: 'Vybrat CSV soubor', paste: 'Nebo vložte CSV', check: 'Zkontrolovat dávku', clear: 'Vyprázdnit dávku', seller: 'Upravit dodavatele a profil',
    format: 'CSV: UTF-8; čárka nebo středník. Data: RRRR-MM-DD. Čísla: desetinná tečka nebo čárka, bez oddělovače tisíců. Identifikátory uchovejte jako text, aby zůstaly úvodní nuly. Kategorie a sazby DPH zadáváte sami; nástroj nerozhoduje o zdanění.',
    columns: 'Povinné názvy sloupců', optional: 'Volitelné názvy sloupců', fresh: 'Po změně CSV, dodavatele nebo profilu dávku znovu zkontrolujte.', busy: 'Kontroluji…',
    checked: 'Zkontrolované faktury: {n}. Před nákupem si prohlédněte částky a doklady níže.', ready: 'Všechny faktury prošly podporovanými kontrolami.', blocked: 'Před nákupem nebo stažením opravte uvedené chyby. Žádná faktura se potichu nevynechá.',
    row: 'Řádek CSV', invoice: 'Faktura', lines: 'Řádky', total: 'K úhradě', preview: 'Zobrazit doklad', errors: 'Chyby', warnings: 'Upozornění',
    buy: 'Odemknout XML na 30 dní za {price} bez DPH', download: 'Stáhnout dávku ZIP', unlocked: 'Váš existující přístup na 30 dní zahrnuje dávkové stahování XML.',
    price: 'Kontrola a náhled dávky jsou zdarma. ZIP používá existující přístup na 30 dní za {price} bez DPH, jednorázově bez předplatného. Nákup jedné faktury dávky neodemyká.',
    return: 'Po platbě se tato dávka otevře na stránce faktur ve stejném jazyce a kartě.', storage: 'Tento prohlížeč neumí uchovat dávku pro návrat. Před platbou si CSV uložte a potom jej znovu načtěte.',
    failure: 'Dávku se nepodařilo zpracovat. Zkontrolujte CSV a zkuste to znovu.', example: 'Načten smyšlený příklad. Níže doplňte vlastního dodavatele a před vystavením nahraďte vzorové odběratele.',
    problems: { size: 'Největší velikost CSV: 1 MB.', empty: 'Přidejte hlavičku a alespoň jeden datový řádek.', rows: 'Nejvýše 500 datových řádků.', quotes: 'Zkontrolujte uvozovky a oddělovače CSV.', header_duplicate: 'Název sloupce se opakuje.', header_unknown: 'Neznámý sloupec. Použijte názvy ze vzoru.', header_missing: 'Chybí povinný sloupec.', columns: 'Řádek má jiný počet sloupců.', characters: 'Nepodporovaný řídicí znak.', required: 'Vyplňte povinné pole.', length: 'Číslo faktury je příliš dlouhé (nejvýše 80 znaků).', currency: 'Použijte třípísmenný kód měny velkými písmeny.', country: 'Použijte dvoupísmenný kód země velkými písmeny.', date: 'Použijte existující datum ve formátu RRRR-MM-DD.', due_date: 'Splatnost je před vystavením.', category: 'Podporované kategorie DPH: S, Z, E, AE, O.', number: 'Neplatné číslo, rozsah nebo přesnost. Nepoužívejte oddělovače tisíců.', rate_category: 'S vyžaduje kladnou sazbu DPH; ostatní podporované kategorie vyžadují nulu.', amount: 'Částka položky přesahuje podporovaný rozsah.', duplicate: 'Shodný řádek se opakuje. Odstraňte duplicitu nebo spojte množství.', conflict: 'Stejné číslo faktury má odlišné údaje odběratele nebo faktury.', invoices: 'Nejvýše 100 faktur.', iban: 'Pro SEPA platbu zadejte platný IBAN dodavatele.' }
  }
};
